- features/docs/defining_steps/snippets.feature
- lib/cucumber/formatter/console.rb
- lib/cucumber/formatter/html.rb
- lib/cucumber/formatter/legacy_api/ast.rb
- spec/cucumber/formatter/console_spec.rb
- spec/cucumber/formatter/html_spec.rb
add more details to snippet scenario to create a failing step
> fix snippet suggestions

- Gemfile
- features/docs/writing_support_code/after_hooks.feature
- lib/cucumber/running_test_case.rb
- spec/cucumber/running_test_case_spec.rb
Depends on https://github.com/cucumber/cucumber-ruby-core/pull/89
> Expose #status on Cucumber::RunningTestCase [#836]

- lib/cucumber/cli/configuration.rb
- lib/cucumber/cli/rerun_file.rb
- spec/cucumber/cli/configuration_spec.rb
- spec/cucumber/cli/rerun_spec.rb
Here is a starter for discussion around modelling the rerun file issue #865. See what you think and let me know. Cheers, Matt
> Model rerun file as a class and add tests - issue #865

- README.md
Update a couple gitter links and the main website URL :hatched_chick:
> Update website and chat url

- features/docs/gherkin/language_help.feature
- features/docs/writing_support_code/after_hooks.feature
- features/lib/step_definitions/language_steps.rb
- lib/cucumber/cli/options.rb
- spec/cucumber/cli/options_spec.rb
Here's a fix for issue #869, including passing Cucumber and RSpec tests. I ran all the tests and everything passes, but let me know if you see anything that needs fixing.
> Fix issue 869

- README.md
> fix link to ruby api documentation

- lib/cucumber/formatter/console.rb
e.g. Pending steps
cc @mattwynne
> Ensure other lines are truncated

- features/docs/formatters/custom_formatter.feature
- lib/cucumber/formatter/io.rb
This was possibly missed from c1768eb91f9399c6533cf2ff22608886514ee5f8.
> Fix extra arg passed to ensure_io.

- features/docs/defining_steps/snippets.feature
- lib/cucumber/rb_support/snippet.rb
- spec/cucumber/rb_support/snippet_spec.rb
> fix snippet data table reference

- .github/ISSUE_TEMPLATE.md
- .github/PULL_REQUEST_TEMPLATE.md
@mattwynne @danascheider This fixes #956. I pushed it to a branch on https://github.com/cucumber/cucumber-ruby/tree/feature/add-templates so you can work on it too.
> Add templates for issues and pull requests

- cucumber.gemspec
cukes.info redirects to https://cucumber.io/
> Update homepage in gemspec

- .travis.yml
- features/docs/gherkin/unicode_table.feature
The master branch build is failing (e.g https://travis-ci.org/cucumber/cucumber-ruby/builds/150020194)
This PR allows us to run Travis on changes in attempts to fix it.
> Fix the build

- .rubocop.yml
- Rakefile
- cucumber.gemspec
Add rubocop to travis and manually disable two cops, which weren't automatically excluded.
> Add rubocop to travis

- CONTRIBUTING.md
Simply add a paragraph to give first-timers a few pointers.
> Add first-timers paragraph

- .rubocop_todo.yml
- gem_tasks/cucumber.rake
- gem_tasks/environment.rake
- lib/cucumber/cli/main.rb
- lib/cucumber/formatter/console.rb
- lib/cucumber/formatter/legacy_api/ast.rb
- lib/cucumber/step_match.rb
> fix Lint/EndAlignment

- .rubocop_todo.yml
- lib/cucumber/multiline_argument/data_table.rb
> fix Lint/UselessAccessModifier

- .rubocop.yml
> Don't check temporary files by rubocop

- .rubocop_todo.yml
- lib/cucumber/formatter/ansicolor.rb
> fix Lint/NestedMethodDefinition

- Gemfile
Environment names in Gemfile looks wrong.
As UNIX environment variables is uppercase, change cucumber_use_git_core to CUCUMBER_USE_GIT_CORE [1]
As CUCUMBER_USE_GIT_WIRE means using https://github.com/cucumber/cucumber-ruby-wire.git right?
[1] https://en.wikipedia.org/wiki/Environment_variable#Unix (though it is not clearly in the document.)
Because maybe it just looks typo.
To easily understand the Gemfile behavior.
For example save below script to /tmp/test.sh.
and change directory to GIT_DIR (cucumber-ruby)
`sh /tmp/test.sh`
```
#!/bin/sh
set -e
ls -d ../cucumber-ruby-core
ls -d ../cucumber-ruby-wire
git clean -fdx
CUCUMBER_USE_GIT_CORE=1 bundle install --path vendor/bundle | \ 
grep 'Fetching https://github.com/cucumber/cucumber-ruby-core.git'
git clean -fdx
bundle install --path …
```
> Update env names correctly

- features/docs/work_in_progress.feature
- features/lib/support/normalise_output.rb
This fixes compatibility with latest Aruba.
Aruba changed its implementation a bit and therefore cucumber test suite needs to be modified. This does not include any modifications of Gemfile.
Keep with upstream.
I am going to apply this patch to be able to properly test Cucumber package on Fedora, where there is already latest Aruba.
> Aruba 0.14.x support

- .travis.yml
Update Ruby 2.4, 2.3 to latest version in .travis.yml.
Want to test on latest version of Ruby 2.3 and 2.4.
Travis will test it.
> Update Ruby 2.4, 2.3 to latest version in .travis.yml.

- .travis.yml
This PR updates CI JRuby to latest release.
> Travis: jruby-9.1.8.0 in CI

- lib/cucumber/events.rb
This PR moves a missing comma.
Moved a comma to make the file parse as Ruby.
See #1082 
I have only inspected it by eye, as yet.
> Events: Typo fix

- .rubocop_todo.yml
- lib/autotest/cucumber_mixin.rb
- lib/cucumber/formatter/html.rb
- lib/cucumber/formatter/legacy_api/adapter.rb
Fixing Style/AndOr violations
* Offense count: 11 according to yml
> Fix Style/AndOr

- CHANGELOG.md
Minor changes. Manual, partial fix for #1182
> Fix links and other updates

- lib/cucumber/constantize.rb
- lib/cucumber/filters/randomizer.rb
- scripts/invite-collaborator
- spec/cucumber/multiline_argument/data_table_spec.rb
Reapplication of the changes I made before. These changes were approved in #1254 
Tied to #1021
> Fix Layout/DotPosition

- .rubocop_todo.yml
- CHANGELOG.md
- lib/cucumber/formatter/json.rb
- spec/cucumber/cli/configuration_spec.rb
- spec/cucumber/formatter/html_spec.rb
- spec/cucumber/formatter/json_spec.rb
- spec/cucumber/formatter/junit_spec.rb
> Fix Layout/ExtraSpacing

- .rubocop_todo.yml
- CHANGELOG.md
- examples/i18n/da/lib/lommeregner.rb
- examples/i18n/it/lib/calcolatrice.rb
- examples/i18n/no/lib/kalkulator.rb
- examples/i18n/ro/lib/calculator.rb
- examples/i18n/sv/lib/kalkulator.rb
- features/lib/support/normalise_output.rb
- lib/cucumber/cli/options.rb
- lib/cucumber/events/step_definition_registered.rb
- lib/cucumber/filters/prepare_world.rb
- lib/cucumber/formatter/console.rb
- lib/cucumber/formatter/html.rb
- spec/cucumber/formatter/json_spec.rb
- Super simple change was done with auto
> Fix Layout/LeadingCommentSpace auto

- .rubocop_todo.yml
- CHANGELOG.md
- lib/cucumber/formatter/unicode.rb
- lib/cucumber/glue/proto_world.rb
- spec/cucumber/cli/options_spec.rb
- spec/cucumber/cli/profile_loader_spec.rb
- spec/cucumber/cli/rerun_spec.rb
- spec/cucumber/configuration_spec.rb
- spec/cucumber/filters/activate_steps_spec.rb
- spec/cucumber/filters/retry_spec.rb
- spec/cucumber/formatter/fail_fast_spec.rb
- spec/cucumber/formatter/html_spec.rb
- spec/cucumber/formatter/json_spec.rb
- spec/cucumber/formatter/pretty_spec.rb
- spec/cucumber/formatter/progress_spec.rb
- spec/cucumber/glue/proto_world_spec.rb
- spec/cucumber/multiline_argument/data_table_spec.rb
- spec/cucumber/project_initializer_spec.rb
- spec/cucumber/rake/task_spec.rb
- spec/cucumber/running_test_case_spec.rb
- spec/cucumber/runtime/support_code_spec.rb
- spec/cucumber/step_match_search_spec.rb
- Removed a bunch of empty lines.
- Also adjusted json spec tests to continue passing
> Fix Layout/EmptyLinesAroundBlockBody

- README.md
I've added links to the latest, up-to-date documentation to the README file, to make it easier for new users to get started.
To ensure that the best documentation resources are easy for users to find.
Not applicable. 
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cucumber/cucumber-ruby/1289)
> README: Added links to additional documentation

- cucumber.gemspec
- features/lib/step_definitions/aruba_steps.rb
- features/lib/step_definitions/cli_steps.rb
- features/lib/step_definitions/cucumber_steps.rb
- features/lib/step_definitions/json_steps.rb
- features/lib/step_definitions/junit_steps.rb
- features/lib/step_definitions/language_steps.rb
- features/lib/support/env.rb
- features/lib/support/feature_factory.rb
- features/lib/support/normalise_output.rb
This PR upgrades our features to use aruba 0.14.
Bumps the development dependency and fixes all deprecations.
To be able to use newer aruba features.
Locally, through `bundle exec cucumber`.
> Update to aruba 0.14

- lib/autotest/cucumber_mixin.rb
This PR removes some old backwards compatibility code.
I noticed this while grepping the repo, so I removed it.
The less unnecessary code we maintain, the better.
> Remove old backwards compat code

- features/lib/support/env.rb
Remove deprecation notices
Fix #1357
CI
> Aruba tweaks

- .circleci/config.yml
- less copy/paste for the commands
- allow failure for JRuby (same as for cucumber-core)
- add test with latest Ruby (allow failure here too)
Not applicable
> Refactor Circle CI config

- appveyor.yml
- lib/cucumber/formatter/json.rb
This should hopefully fix #1392
> Force ANSICON install on appveyor

- .circleci/config.yml
Fix the build errors we currently have when running Cucumber against the Compatibility Kit.
> Fix CCK errors

- release-notes/4.0.0rc4.md
A bit late, but still want to merge before cutting rc5
> Release notes rc4

- .circleci/config.yml
- cucumber.gemspec
- features/docs/formatters/message.feature
- lib/cucumber/formatter/message.rb
- lib/cucumber/platform.rb
- lib/cucumber/runtime.rb
- spec/cucumber/runtime_spec.rb
See https://github.com/cucumber/cucumber/pull/976
> Emit Meta message at beginning of run

- CHANGELOG.md
- lib/cucumber/formatter/http_io.rb
- spec/cucumber/formatter/http_io_spec.rb
> Do not send headers on 2nd request (--publish)

- spec/cucumber/cli/options_spec.rb
- spec/cucumber/step_match_search_spec.rb
> Fixed typo with misspell

- CHANGELOG.md
- features/docs/cli/dry_run.feature
- lib/cucumber/runtime.rb
Reverts cucumber/cucumber-ruby#1537
> Revert "Add support for message formatters with dry runs"

- .github/workflows/cucumber-ruby.yml
- CHANGELOG.md
- features/docs/cli/dry_run.feature
- lib/cucumber/runtime.rb
- spec/cucumber/formatter/message_spec.rb
- spec/cucumber/formatter/spec_helper.rb
Fixes #1496 and #1488
I've just applied the suggestion from @cbochs in #1496, it seems to work as expected.
It did not get well previously actually :(
> Fix dry run with messages

- CHANGELOG.md
- features/docs/cli/publish_banner.feature
- lib/cucumber/formatter/publish_banner_printer.rb
- spec/cucumber/formatter/publish_banner_printer_spec.rb
Many users need help setting environment variables
This updates the banner to point to new docs added in cucumber/docs#636
> Point to https://cucumber.io/docs/cucumber/environment-variables/

- .rubocop.yml
- lib/cucumber/configuration.rb
- lib/cucumber/formatter/backtrace_filter.rb
- lib/cucumber/formatter/io.rb
- lib/cucumber/formatter/junit.rb
- spec/cucumber/formatter/junit_spec.rb
- spec/cucumber/glue/registry_and_more_spec.rb
- spec/cucumber/project_initializer_spec.rb
> Update rubocop config to allow inner slashes in regexp

- CHANGELOG.md
I am about to release v8.0.0
Is it fine?
> Prepare Release v8.0.0

- renovate.json
> Enable dependency dashboard (temporarily)

- .github/dependabot.yml
Signed-off-by: Ashish Kurmi <akurmi@stepsecurity.io>
Please include a summary of the change, mentioning any issues that are fixed (or partially fixed) by this change.
Please also include relevant motivation and context.
e.g. "Fixes #99"
- New feature (non-breaking change which adds new behaviour)
- This change requires an update of [cucumber.io/docs](https://cucumber.io/docs)
If your change may impact future contributors, explain it here, and …
> update dependabot for GitHub Actions

- lib/cucumber/rake/task.rb
Lint fix an upcoming linting failure.
Fixes the build failure in #1679, which uses a new rule.
> Lint: Style/SafeNavigation

- Gemfile
Reverts cucumber/cucumber-ruby#1712
> Revert "Update dependency rubocop to v1.55.1"

- Gemfile
Reverts cucumber/cucumber-ruby#1718
> Revert "Update dependency rubocop to v1.56.0"

- Gemfile
This reverts commit 4f66002a63781e62aee0f4fc5c65d07f3c3f50ae.
Please include a summary of the change, mentioning any issues that are fixed (or partially fixed) by this change.
Please also include relevant motivation and context.
e.g. "Fixes #99"
- New feature (non-breaking change which adds new behaviour)
- This change requires an update of [cucumber.io/docs](https://cucumber.io/docs)
If your change may impact future contributors, explain it …
> Revert "Update dependency rubocop to v1.56.0 (#1720)"

- Gemfile
Reverts cucumber/cucumber-ruby#1724
> Revert "Update dependency rubocop to v1.56.2"

- .github/FUNDING.yml
See discussion on https://github.com/cucumber/.github/pull/42
> chore: add github sponsors to funding

- compatibility/features/attachments/attachments_steps.rb
This fixes the CI. It also supports the changes made in https://github.com/cucumber/compatibility-kit/pull/106
> bugfix: Add step for text/uri-list example
