- lib/cucumber/rb_support/rb_transform.rb
- spec/cucumber/rb_support/rb_transform_spec.rb
Fixes transformation of lookbehind/lookahead.
Before fix: 
```ruby
transform(/^xy(?=z)/).to_s) #=> "xy(?:?=z)"
```
After fix
```ruby
transform(/^xy(?=z)/).to_s) #=> "xy(?=z)"
```
It works for positive/negative lookahead/lookbehind and for named capture groups
> Fix transformation of regex with lookahead/lookbehind

- lib/cucumber/cli/options.rb
- lib/cucumber/project_initializer.rb
- spec/cucumber/project_initializer_spec.rb
Adds an init feature to the cucumber cli tool.  This feature constructs the standard folder structure for a project using cucumber.
> Feature: cucumber --init

- lib/cucumber/rb_support/snippet.rb
- spec/cucumber/rb_support/snippet_spec.rb
Imagine I'm writing a new scenario that includes something similar to this:
```cucumber
When I press "Submit" button
Then I should see "can't be blank" validation error on "Email"
```
first time I run this new scenario, cucumber will suggest me code snippets to start implementing missing steps. The snippet for validation step would be
```ruby
Then(/^I should see "(.*?)" validation error on "(.*?)"$/) do |arg1, arg2|
pending # express the regexp above with the code you wish you had
end
```
Later I add another scenario that includes this:
```cucumber
Then I should see "foobar"
```
and cucumber, again, helpfully suggest a snippet to start implementing the step:
```ruby
Then(/^I should see "(.*?)"$/) do |arg1|
```
The problem is, the suggested regexp also matches everything, a previously …
> Suggested regexes are bad and result in ambiguous matches

- spec/cucumber/formatter/junit_spec.rb
@mattwynne Started looking at #124.  For now, this failing unit test highlights the problem.  I'm still looking at [formatter/junit.rb](https://github.com/cucumber/cucumber/blob/master/lib/cucumber/formatter/junit.rb) to see if that's the place to handle `@option[:expand]`
> fix issue #124 - JUnit expand option

- features/docs/exception_in_around_hook.feature
- features/docs/wire_protocol/handle_unexpected_response.feature
- features/docs/writing_support_code/around_hooks.feature
- lib/cucumber/filters/prepare_world.rb
- lib/cucumber/formatter/legacy_api/adapter.rb
- spec/cucumber/formatter/legacy_api/adapter_spec.rb
- spec/cucumber/formatter/pretty_spec.rb
This supersedes #640.
Based on @maxlinc's example this scenario demonstrates that the world an around hook is being instance_exec'd on is not quite right.
For the first scenario, self is nil, and the next scenario the world is remembered from the previous scenario.
> Around hooks not executing in correct world context

- features/docs/cli/specifying_multiple_formatters.feature
- lib/cucumber/cli/configuration.rb
- lib/cucumber/cli/options.rb
- spec/cucumber/cli/configuration_spec.rb
- spec/cucumber/cli/options_spec.rb
Somehow the check for multiple formatters using stdout is disabled when using profiles (even when the profile does not define any formatter). See failing scenario.
The root cause of this behaviour is the [logic for replacing the stdout formatter form the profile with the stdout formatter from the command line options](https://github.com/cucumber/cucumber/blob/13c621d2ea30733ddffdbfac42e2db0b39694f07/lib/cucumber/cli/options.rb#L366). Since the code remove all but the first stdout formatters, you can define several stdout formatters on the command line without getting an error when using profiles, but only the first one will actually be used. This behaviour cased some confusion [in this mailing list thread](https://groups.google.com/forum/#!topic/cukes/F2MM0pB9KTI).
To cover all cases, the …
> The check for multiple formatters using stdout is disabled when using profiles

- lib/cucumber/multiline_argument/data_table.rb
- spec/cucumber/multiline_argument/data_table_spec.rb
New method allows data table to be accessed as an Array of Hashes with symbols as keys in step definitions. #840
> Cucumber::MultilineArgument::DataTable#symbolic_hashes

- features/docs/cli/finding_steps.feature
- lib/cucumber/cli/configuration.rb
In general there seem to be some weird dependencies (or lack there of) between
configuration options and information in `Cucumber::Cli::Configuration#feature_files`
that could probably be clarified with a little refactoring.
One example that this feature exposed directly is that
`Cucumber::Cli::Configuration#feature_files` does not
depend on `Cucumber::Cli::Configuration#feature_dirs` though their names
certainly imply dependence.
I had deleted `Cucumber::Cli::Configuration#feature_dirs` to eliminate
the confusion, but added it back in when I realized it was used in
`features/docs/post_configuration_hook.feature`.
I took a stab at re-architecting the configuration code awhile back, but got mired and gave up. Just realized I never submitted this pull request.
Looks like there's plans to …
> Default require path to features unless specified explicitly.

- features/docs/formatters/junit_formatter.feature
- lib/cucumber/formatter/backtrace_filter.rb
- lib/cucumber/formatter/junit.rb
- lib/cucumber/formatter/legacy_api/adapter.rb
To make the result object of the new formatter api directly usable in the formatters (and not rely on classes in the LegacyApi module):
* move the BacktraceFilter class to the Cucumber::Formatter module
* move the appending of the step backtrace line to Cucumber-ruby-core (cucumber/cucumber-ruby-core#88)
* apply the backtrace filter on the result in the call to the new formatter api methods
Depends on cucumber/cucumber-ruby-core#88
Fixes #833.
> Make the result arguments of the new formatter api produce the proper backtrace

- features/docs/formatters/html_formatter.feature
- lib/cucumber/formatter/legacy_api/ast.rb
- spec/cucumber/formatter/html_spec.rb
> Properly close HTML formatter pre tag for leading comment

- spec/cucumber/formatter/html_spec.rb
Between 1.3.19 and 2.0.0, if you have a comment in a feature file at the scenario level, the html formatter does not include it in the output.  This failing spec demonstrates that behaviour.
> Failing spec for html formatter scenario-level comment

- lib/cucumber/formatter/junit.rb
Jenkins chokes on JUnit XML results that contain no `testcase` elements, a scenario that can arise due to issue #124. Backporting the fix to the latter proved to be insanely difficult so I wrote this expedient workaround that avoids writing out XML where no test results were actually handled.
> Avoid writing JUnit results that have no testcases

- features/docs/formatters/junit_formatter.feature
- lib/cucumber/formatter/junit.rb
- spec/cucumber/formatter/junit_spec.rb
The rewrite does also automatically fixed some problems regarding Scenario Outline test cases. Multiple failing test cases from the same Examples table, and pending and undefined test cases from Scenario Outlines in strict mode, have not been handled properly.
In addition the intercepted stdout and stderr data are moved from the testsuite elements (which representing Features) to the testcase element (fd5e38e). Stdout and stderr elements are already created (but empty) for testcase elements. It makes more sense to put the intercepted stdout and stderr in the testcase, and having empty stdout and stderr elements there (which stated "nothing was intercepted") seems to misinformation is anything.
The final change (4f3ebda) requires cucumber/cucumber-ruby-core#92, I think a …
> Rewrite the JUnit Formatter to the new formatter Api

- features/docs/defining_steps/printing_messages.feature
- features/docs/formatters/usage_formatter.feature
- features/docs/gherkin/outlines.feature
- lib/cucumber/formatter/console.rb
- lib/cucumber/formatter/duration_extractor.rb
- lib/cucumber/formatter/legacy_api/runtime_facade.rb
- lib/cucumber/formatter/pretty.rb
- lib/cucumber/formatter/progress.rb
- lib/cucumber/formatter/usage.rb
- spec/cucumber/formatter/progress_spec.rb
Since these formatters are related through inheritance they are modified together. Since the Stepdef formatter neither defined any method of the old formatter api, nor defines any methods of the new formatter api, it is updated to the new formatter api by the changes in the Progress and Usage formatters.
Also some deficiencies of the Progress formatter are fixed, both that outline steps were printed as skipped (fixes #316), and some cases where the printed progress characters did not match the step count in the summary ([here only 8 '-' were printed, but the step count says 11 skipped](https://github.com/cucumber/cucumber/blob/09b0ae424233e5c429bdeb0b9d29f34846d52e09/features/docs/formatters/usage_formatter.feature#L38-L55)).
Related to #839.
> Rewrite the Progress, Usage, Stepdefs formatters to the new formatter api

- features/docs/cli/dry_run.feature
- features/docs/cli/run_specific_scenarios.feature
- features/docs/defining_steps/nested_steps.feature
- features/docs/defining_steps/skip_scenario.feature
- features/docs/exception_in_around_hook.feature
- features/docs/formatters/usage_formatter.feature
- features/docs/gherkin/background.feature
- features/docs/gherkin/outlines.feature
- features/docs/gherkin/using_descriptions.feature
- lib/cucumber/cli/options.rb
- lib/cucumber/formatter/console.rb
- spec/cucumber/cli/configuration_spec.rb
- spec/cucumber/cli/options_spec.rb
This attempts to resolve #816 
I'm not able to remove the [referenced hack](https://github.com/cucumber/cucumber/blob/master/features/lib/support/normalise_output.rb#L11) just yet, but I'll keep working on it.
> don't print the duration in quiet mode

- features/lib/step_definitions/junit_steps.rb
- In 2014, this was a trouble https://github.com/cucumber/cucumber/pull/669 but nowadays, String and DocStrings compare fine.
> [cleanup] Nowadays, DocString compares to Strings

- features/docs/formatters/rerun_formatter.feature
- lib/cucumber/formatter/rerun.rb
- spec/cucumber/formatter/rerun_spec.rb
I think the invariant for the behaviour of the Rerun Formatter should be:
When the exit code is zero => the Rerun formatter output is empty
When the exit code is non-zero => the Rerun formatter output is not empty
This PR changes the behaviour the Rerun Formatter to fulfil this invariant.
The final change (fc356b1) requires cucumber/cucumber-ruby-core#92.
> Make the Rerun Formatter consistent with the exit code

- features/docs/formatters/json_formatter.feature
- features/lib/support/normalise_output.rb
- lib/cucumber/filters/prepare_world.rb
- lib/cucumber/formatter/json.rb
- lib/cucumber/hooks.rb
- lib/cucumber/rb_support/rb_hook.rb
- lib/cucumber/runtime/after_hooks.rb
- lib/cucumber/runtime/before_hooks.rb
- lib/cucumber/runtime/step_hooks.rb
- lib/cucumber/runtime/support_code.rb
- lib/cucumber/step_match.rb
- spec/cucumber/formatter/json_spec.rb
- spec/cucumber/formatter/legacy_api/adapter_spec.rb
The main behavioural goal of the PR is to included results for test cases from Scenario Outlines also when the `--expand` option is not used (currently the `--expand` option is need to usable data when using Scenario Outlines).
A secondary behavioural goal is to align the produced Json file with what Cucumber-JVM produces, for the benefit of people that develop third party tools to be used together with the Cucumber version. The first tools that comes to mind are [the Masterthought tools](http://www.masterthought.net/section/cucumber-reporting) and [the Bamboo plugin](https://marketplace.atlassian.com/plugins/com.hindsighttesting.behave.cucumber-bamboo-plugin). This means that:
* results for all executed steps are included (that means the Background steps are included each time they are …
> Rewrite the Json Formatter to use the new formatter api 

- CONTRIBUTING.md
As discussed in https://github.com/cucumber/cucumber-ruby-core/pull/93#issuecomment-119237258.
For the Rubygems email, see the the profile link.
> Add Björn Rasmusson as release manager

- features/docs/defining_steps/nested_steps_with_second_arg.feature
- features/docs/gherkin/doc_strings.feature
- lib/cucumber/multiline_argument/doc_string.rb
- lib/cucumber/rb_support/rb_world.rb
With this patch, `DocString` objects are now true `String` objects, and not a `Cucumber::MultilineArgument::DocString` object.
I understand that the intention with `Cucumber::MultilineArgument::DocString` is that it behaves just like a `String`, but it doesn't. For example, `expect(some_string).to eq(some_doc_string)` causes an unreadable error message with a `DocString`, but a nice one (with a diff) for a `String`.
Furthermore, `DocString` is an implementation detail of Cucumber that users shouldn't be concerned with. In DDD speak, these are two (or perhaps three) different bounded contexts: Parsing, (Execution) and user code.
A side-effect of this change is that the `content_type` attribute is no longer available. That's fine - I can't think of a reason why users would need this. The …
> Pass DocString as String

- features/docs/api/listen_for_events.feature
- features/docs/extending_cucumber/custom_formatter.feature
- lib/cucumber/configuration.rb
- lib/cucumber/events.rb
- lib/cucumber/events/after_test_case.rb
- lib/cucumber/events/after_test_step.rb
- lib/cucumber/events/before_test_case.rb
- lib/cucumber/events/before_test_step.rb
- lib/cucumber/events/bus.rb
- lib/cucumber/events/step_match.rb
- lib/cucumber/formatter/event_bus_report.rb
- lib/cucumber/formatter/io.rb
- lib/cucumber/formatter/usage.rb
- lib/cucumber/runtime.rb
- lib/cucumber/runtime/support_code.rb
- lib/cucumber/step_match.rb
- spec/cucumber/cli/main_spec.rb
- spec/cucumber/configuration_spec.rb
- spec/cucumber/events/bus_spec.rb
- spec/cucumber/formatter/event_bus_report_spec.rb
With this change, clients both within the Cucumber codebase and built by our users, can consume events about various things that happen as your tests run.
For example:
* when a test case finishes
* when a step definition is matched
This should help us remove some of the ugly coupling between different parts of the code, and allow for more flexiblity in the API for users who want to build formatters and other tools.
Feedback please!
The intention is that this change is backwards compatible, with the idea that it will become the mandatory API for writing formatters from version 3.0
> Introduce Event Bus (WIP)

- lib/cucumber.rb
- lib/cucumber/cli/configuration.rb
- lib/cucumber/cli/options.rb
- lib/cucumber/configuration.rb
- spec/cucumber_spec.rb
This gives us way to use `Hash(object)` in cucumber including ruby 1.9.
I'm not sure if its a good idea to add this directly to Kernel though? There's a risk someone could use it in their app unknowingly and have passing tests but fail in production when cucumber is not required?
We could instead add an explicit `Cucumber::Hash` method to isolate this change against that?
> Backport a version of Ruby > 2 Hash method

- lib/cucumber/configuration.rb
- spec/cucumber/configuration_spec.rb
Without this change, `factory.new(@configuration.with_options(out_stream: out_stream))` in Cucumber::Runtime#create_formatter doesn't actually changed the `out_stream` from STDOUT in the default configuration because the merge order was `new_options.merge(@options)`, so any keys in both `new_options` and `@options`, like `:out_stream`, would have the value from `@options` win.
The specs weren't catching this problem because `with_options` was being called on `Configuration.new`, which had no keys set.  I changed in spec in 63d4c37 to reveal the bug and fixed it in 067215c.
This bug may have manifested by users unable to override the --out from STDOUT when using new formatters that have `initialize(configuration)` instead of the legacy `initialize/3`
> Fix Configuration.with_options merge direction

- lib/cucumber/rb_support/rb_world.rb
Fixed a bug that was causing the delayed output of #puts calls to be
affected by modifications to its arguments that occurred between the
time #puts was called and the time that its output was actually
displayed.
Fixes #915.
> Output bug fix.

- README.md
SVG badges are much better readable on hi-res displays. See https://github.com/Originate/cucumber-ruby vs https://github.com/cucumber/cucumber-ruby.
> Convert badges to SVG

- lib/cucumber/formatter/json.rb
I started running into issues when formatting cucumber reports as JSON. With the default JSON gem (also I believe 'oj' and 'yajl'), it seems that the JSON formatter has started stringifying the `location` object on steps as hashes instead of using the `to_s` method found in [cucumber-ruby-core](https://github.com/cucumber/cucumber-ruby-core/blob/master/lib/cucumber/core/ast/location.rb#L75).
Desired Output:
```
"location": "features/step_definitions/selenium/selenium.rb:8"
```
Undesired Output:
```
"location": {
"filepath": {
"filename": "json_spec-1.1.4/lib/json_spec/cucumber.rb"
},
"lines": {
"data": [
"5"
]
}
}
```
This issue does not occur when running the spec tests using the `json_spec` gem, but happens every time with the classic ruby JSON gem (1.8.3). I added a `to_s` call when …
> stringifying location for more consistent json parsing - address #945

- Gemfile
Build fails on ruby 1.9.3 due to ruby version conflict for a gem.
This `cucumber-ruby`-[build](https://travis-ci.org/cucumber/cucumber-ruby/jobs/118065154) fails on ruby 1.9.3. A newer version of `mime-types` requires ruby 2.0, so installing it on ruby 1.9.3 fails. This gem is required by 'capybara'. `capybara` is required by the devs deps in the gemspec.
~~~
Gem::InstallError: mime-types-data requires Ruby version >= 2.0.
~~~
Make the build pass again.
This is tested via Travis.
> Lock mime-types-data to older version

- examples/i18n/eo/features/adicio.feature
- examples/i18n/eo/features/divido.feature
- examples/i18n/eo/features/step_definitions/calculator_steps.rb
The existing Esperanto translations are literal translations of the original English text, and not especially idiomatic. They also contain a few errors. I have re-written them with better translations.
Please note that this also requires my improved Esperanto translations for Gherkin.
> [i18n] Improve the Esperanto translation

- lib/cucumber/rake/task.rb
- spec/cucumber/rake/task_spec.rb
Tests around the Rake task were already pretty sparse. So tests against existing behavior were added first, then failing tests for the new array support, and finally implementation (and refactoring of tests/implementation).
Can be squashed if desired.
> Allow Rake task to accept multiple profiles. fixes #905

- lib/cucumber/ast/has_steps.rb
Some monkey patched implementations of `String#indent`, such as Active
Support's, do not handle negative values (see issue #620). This behavior
isn't strictly a bug in Cucumber but a lower bound of 0 in
`#source_indent` would mitigate the occurrences of related errors.
> Avoid negative `Cucumber::Ast::HasSteps#source_indent`

- lib/cucumber/cli/rerun_file.rb
- spec/cucumber/cli/rerun_spec.rb
Relates to #927 - handle more weird rerun formats.
> Issue #927 - handle even more exotic rerun file formats seen in the wild

- features/docs/test_step_available_in_after_step_hook.feature
- features/docs/writing_support_code/after_step_hooks.feature
- lib/cucumber/rb_support/rb_hook.rb
- lib/cucumber/runtime/step_hooks.rb
Working on Add step to AfterStep #450 
Do you think the argument list should be consistent with how formatters work or will it potentially cause problems moving the current argument out of its position as first argument?
> Adding Test Step in AfterStep feature file.

- lib/cucumber/runtime/for_programming_languages.rb
Cucumber 1.3.20, the following code.
```ruby 
Feature: Test feature
Scenario: Test scenario
Given The folowing users exist
| name | email         |
| foo     | foo@foo.com |
| bbb    | bbb@bbb.com |
Given /^The folowing users exist$/ do |table|
table.rows.each do |name, email|
Transform(name)
end
end
Transform /foo/ do |ignore|
'Foo'
end
```
The result is this.
```
1 scenario (1 passed)
1 step (1 passed)
0m0.006s
```
But, cucumber 2.3.2, the result is...
```
Feature: Test feature
Scenario: Test scenario          # features/test.feature:2
Given The folowing users exist # features/step_definitions/test_step.rb:1
| name | email                 #|
| foo     | foo@foo.com |
| bbb    | bbb@bbb.com |
undefined method `support_code' for #<Cucumber::Runtime::ForProgrammingLanguages:0x007fa082ae8880 …
```
> "Fix undefined method `support_code'" in Transform method

- features/docs/cli/randomize.feature
- lib/cucumber/runtime.rb
This documents the desired behaviour of the random order option across multiple features and corrects the ordering of filters within `runtime.rb` in order to run scenarios in a genuinely random order.
Previously, using `--order=random` resulted in the order of scenarios being randomised within a feature, but features themselves always proceeded in alphabetical (or ASCIIbetical) order based on their file path, i.e.:
Feature: 1
Scenario: 1B
Scenario: 1A
Feature: 2
Scenario: 2B
Scenario: 2A
Although `Randomizer` does indeed shuffle the scenarios, it was followed in the filter chain by `LocationsFilter` which groups scenarios by file path. Moving `Randomizer` later in the chain avoids this.
Now, each scenario is run in random order regardless of the name or path of the feature:
Feature: 1 …
> Run scenarios in fully random order

- features/docs/extending_cucumber/custom_formatter.feature
- lib/cucumber/cli/main.rb
@maxmeyer this is my suggestion for how to deal with the issue we've
been discussing in #958, at least for now.
I think I understand your issue now (it's s00oo much easier with real code
in my hands sometimes!) and what I may have missed suggesting is to use
the `@spawn` tag which uses the "tranditional" adapter for Aruba instead
of the in-process one.
This commit shows you how you'd do that.
> Demonstrate suggested way to capture output

- lib/cucumber/step_match.rb
> fix typo in lib/cucumber/step_match.rb

- features/docs/cli/randomize.feature
- lib/cucumber/filters/randomizer.rb
This makes two important changes to random ordering.
1. Using the `--order=random` option with a particular seed will now produce the **same order** on every Ruby interpreter.
2. The order is **stable**, so that if step A runs before step B with a given seed, it will still do so for that seed and suite even if intervening steps are skipped.
Previously, the random seed would produce consistent results on a given interpreter, but this could not always be reproduced on another version of Ruby. This occurred because `Array#shuffle` is implemented differently in different interpreters: Ruby 1.9.3 and JRuby 1.7.x share one implementation, whilst Ruby 2.x has a different one.
Stability of ordering is a necessary precondition for using bisection to resolve an ordering dependency (as RSpec can …
> Make random order stable and platform-independent

- .travis.yml
- features/docs/cli/retry_failing_tests.feature
- features/lib/step_definitions/cucumber_steps.rb
- features/lib/step_definitions/retry_steps.rb
- lib/cucumber/cli/configuration.rb
- lib/cucumber/cli/options.rb
- lib/cucumber/configuration.rb
- lib/cucumber/filters/retry.rb
- spec/cucumber/cli/configuration_spec.rb
- spec/cucumber/cli/options_spec.rb
- spec/cucumber/filters/retry_spec.rb
Here are the features I wrote up for #882. Let me know what you think, @mattwynne and @brasmusson. Travis isn't passing but it's those wire protocol features again - shouldn't have been affected by what I wrote.
> Add --retry option to retry failed tests as part of the same run

- Gemfile
Replace git through https as transport protocol  since the latter is p…roxyable
If a developer is required to access the WWW via a HTTP proxy, git cannot be used as transport protocol since it is not proxyable. `git` is set in https://github.com/cucumber/cucumber-ruby/blob/master/Gemfile#L11.
Old:
~~~
gem 'cucumber-core', :git => "git://github.com/cucumber/cucumber-ruby-core.git"
~~~
New:
~~~
gem 'cucumber-core', :git => "https://github.com/cucumber/cucumber-ruby-core.git"
~~~
There might be other cucumber projects where such a change makes sense.
In bigger companies the use of HTTP proxies is quite common. There's not direct access from a laptop/computer to the WWW. Using `git` as transport protocol is a burden for new developers from such an environment as a local change is required …
> Replace git through https as transport protocol

- lib/cucumber/cli/options.rb
This PR refactors the `#parse!` method for the `Cucumber::Cli::Options` class.
I extracted descriptions and option handlers to new private methods and turned the `opts.on` blocks into single lines.
I noticed that Code Climate had rated this class F, and when I looked at the code, I could see why. I think the new way is more readable.
I tested the changes using the existing test suite to check for regressions. Since I didn't add or remove functionality, new tests were not required.
> Refactor cli options

- features/docs/defining_steps/printing_messages.feature
- lib/cucumber/configuration.rb
- lib/cucumber/events.rb
- lib/cucumber/events/step_definition_registered.rb
- lib/cucumber/formatter/console.rb
- lib/cucumber/formatter/progress.rb
- lib/cucumber/formatter/summary.rb
- lib/cucumber/formatter/usage.rb
- lib/cucumber/rb_support/rb_language.rb
- lib/cucumber/runtime.rb
- spec/cucumber/formatter/progress_spec.rb
Change the Progress, Usage and Stepdef formatter use events and also the new initialize method signature.
For the Usage formatter to be able to find out which step definitions that were not matched to any step, the StepDefinitionLoaded event is added. This also means that the step definitions are loaded after the AfterConfigurationHooks have been executed and the formatter have been created, whereas the support files are loaded before the AfterConfigurationHooks are executed.
The API:s of Cucumber::Formatter::Console and Cucumber::Formatter::Summary are extended, but are backward compatible as they are use both by the Pretty formatter and existing custom formatters.
To simplify the usage of Cucumber::Core::Test::Result::Summary its API has been extended in …
> Change the Progress, Usage and Stepdef formatter use events

- features/docs/cli/help.feature
- features/lib/step_definitions/cli_steps.rb
- lib/cucumber/cli/options.rb
Fix regression displaying CLI help
Added a test, added a quick fix.
`cucumber --help` was broken.
Added a new feature - surprised we didn't already have one!
> Fix regression displaying CLI help

- Gemfile
- History.md
This PR resolves issue #961, where `bundle install` fails because of `cucumber-ruby-wire`. It makes changes to the Gemfile so that if the user does not have `cucumber-ruby-wire` locally, or doesn't have it in the expected location, it will be fetched from git instead of erroring out.
Added a conditional to the Gemfile to check whether the `cucumber-ruby-wire` code exists locally in the expected location and, if not, gets it from git instead.
This issue was causing errors in `bundle install`, making it harder for developers to work on Cucumber.
Gemfile change probably doesn't need tests.
- [x ] Bug fix (non-breaking change which fixes an issue)
> Resolve issue 961

- Gemfile
This PR changes `git://` to `https://` in the Gemfile, correcting a change made in #983.
This change will enable forwarding via HTTP proxies.
> Change git:// to https://

- lib/cucumber/formatter/html.rb
- spec/cucumber/formatter/html_spec.rb
An alternative to #910.  #910 attempts to fix the problem by altering the regular expression, which seems strange to me.  It could be that the regular expression needs fixing but I am experiencing this bug and I don't have `ENV['TM_PROJECT_DIRECTORY']` set at all.  If `ENV['TM_PROJECT_DIRECTORY']` isn't set at all why even try to match the regular expression against the input?
It should be noted that `line` is not in fact a single line.  It is the backtrace array which has already been joined with newlines.
I also noticed that the code is running `delete_if` on the array it gets from  `exception`.  Mutating objects that do not belong to us is bad practice.  A better practice would be to use `reject` instead to get a new array.  I'm keeping this PR focused on the actual bug though.
> fix HTML formatter backtrace duplicate line bug

- .gitignore
- CONTRIBUTING.md
- Gemfile
I normally use some gems for debugging etc. which are quite "individual". This PR adds the possibility to have an local `Gemfile.local` which is not part of the cucumber repository. In this Gemfile a developer can have "his/her" private gems which are not shared with the community because each developer has his/her own workflow/tool chain.
Using a git ignored `Gemfile.local` gives developers a "convenient" way to have their own gems installed - e.g `pry` + `byebug` - while not littering the projects `Gemfile` with developer's specific gems. If you're interested I can also submit a PR for cucumber-ruby-core.
Developer can have "his/her" private gems which are not shared with the community because each developer has his/her own workflow/tool chain.
Tested locally with own `Gemfile.local` …
> Load gems from local Gemfile which is not part of the repository

- spec/cucumber/rb_support/rb_language_spec.rb
Previously spec didn't create file before trying to load it. While it's a minor problem, it does not reproduce real test case. Also, I've changed the test file name, as it was changing the actual README.md of the project in the test.
It improves quality of tests.
Running locally, Travis build of fork is [green](https://travis-ci.org/brain-geek/cucumber-ruby/builds/137108960).
> Fix typo in loading file specs

- lib/cucumber/formatter/backtrace_filter.rb
- spec/cucumber/formatter/backtrace_filter_spec.rb
- Add `.rbenv/.*/bin/bundle` to backtrace filters
- Refactor backtrace filtering
- Add unit tests for backtrace filtering
It resolves https://github.com/cucumber/cucumber-ruby/issues/1017.
> Fix #1017 - missing backtrace filter

- .rubocop_todo.yml
- lib/cucumber/cli/profile_loader.rb
- lib/cucumber/formatter/ansicolor.rb
- lib/cucumber/formatter/html.rb
- lib/cucumber/formatter/legacy_api/results.rb
- lib/cucumber/multiline_argument/data_table.rb
Partial fix for #1021 
* ```Hash#has_key?``` => ```Hash#key?``` due to [DEPRECATION](https://redmine.ruby-lang.org/issues/5555#note-10)
* Lint/BlockAlignment
* Lint/DefEndAlignment
> Fix rubocop violations

- .rubocop.yml
- features/lib/support/normalise_output.rb
- lib/autotest/cucumber_mixin.rb
- lib/cucumber/cli/options.rb
- lib/cucumber/formatter/console.rb
- lib/cucumber/formatter/json.rb
- lib/cucumber/formatter/legacy_api/adapter.rb
- lib/cucumber/formatter/legacy_api/ast.rb
- lib/cucumber/formatter/legacy_api/results.rb
- lib/cucumber/formatter/progress.rb
- lib/cucumber/formatter/usage.rb
- lib/cucumber/rb_support/rb_transform.rb
- lib/cucumber/runtime/user_interface.rb
- spec/cucumber/formatter/json_spec.rb
- spec/cucumber/formatter/junit_spec.rb
This PR is part of my effort in setting up `rubocop`.
It progresses #1021, by removing the violations ignored in `.rubocop.yml` file. It's a bigg-ish PR but once it will merged we can track the violations using only `.rubocop_todo.yml`.
> Fix style violations

- .rubocop_todo.yml
- lib/autotest/cucumber_mixin.rb
> fix Lint/NonLocalExitFromIterator

- .rubocop_todo.yml
- lib/cucumber/formatter/html.rb
- lib/cucumber/rb_support/rb_language.rb
- lib/cucumber/rb_support/rb_step_definition.rb
- lib/cucumber/rb_support/snippet.rb
Fixes rubocop violation Lint/StringConversionInInterpolation
All the `*.to_s` calls inside interpolations have been fixed: Removed `.to_s`.
This change is required to satisfy the ruboxop requirement related to Lint/StringConversionInInterpolation
Refs #1021 
No new tests. Existing tests are green (with `bundle exec rake`). Rubocop is happy.
N/A
> Fixes rubocop violation Lint/StringConversionInInterpolation

- .rubocop_todo.yml
- lib/cucumber/formatter/duration.rb
- lib/cucumber/formatter/junit.rb
- lib/cucumber/formatter/usage.rb
- lib/cucumber/rake/task.rb
- lib/cucumber/rb_support/rb_world.rb
- lib/cucumber/rb_support/snippet.rb
It fixes the rubocop violation `Style/FormatString`. The suggestion from rubocop is to use `Kernel#format` instead of the cryptic `String#%`. Also, it favours the `Kernel#format` over the `Kernal#sprintf` although the former is alias of the latter, just to make sure that we are using one method consistently throughout the code base.
1. I have replaced all the `Kernel#sprintf` calls with `Kernel#format` calls. 
2. I have also replaced all the `String#%` calls with `Kernel#format` calls.
This change is required to comply with rubocop suggestion to be using `Kernel#format` vs `Kernel#sprintf` and `String#%`.
Refs #1021 
With `bundle exec rake` everything is green.
N/A
> Fixes rubocop violation Style/FormatString

- .rubocop_todo.yml
- features/lib/support/feature_factory.rb
- lib/cucumber/configuration.rb
- lib/cucumber/formatter/json.rb
Fixes rubocop violation Performance/StringReplacement
Changes to stop using `.gsub()` to do character replacements, but use `,tr()` instead. Also, when
`.gsub()` was used to delete a character, we are now using `.delete()`.
This change makes sure our code is compliant with the ruboxop `Performance/StringReplacemenet` rule
Refs #1021 
I have run all the tests with `bundle exec rake` and everything is green. Rubocop is happy too.
N/A
> Fixes rubocop violation Performance/StringReplacement

- .rubocop_todo.yml
- examples/watir/features/support/screenshots.rb
- lib/cucumber/cli/configuration.rb
- lib/cucumber/deprecate.rb
- lib/cucumber/formatter/html.rb
- lib/cucumber/formatter/json.rb
- lib/cucumber/formatter/junit.rb
- lib/cucumber/formatter/legacy_api/adapter.rb
- lib/cucumber/formatter/legacy_api/ast.rb
- lib/cucumber/formatter/pretty.rb
- lib/cucumber/formatter/steps.rb
- lib/cucumber/hooks.rb
- lib/cucumber/multiline_argument.rb
- lib/cucumber/multiline_argument/data_table.rb
- lib/cucumber/rake/task.rb
- lib/cucumber/rb_support/snippet.rb
- lib/cucumber/rspec/disable_option_parser.rb
- lib/cucumber/running_test_case.rb
- lib/cucumber/runtime.rb
- lib/cucumber/runtime/for_programming_languages.rb
- lib/cucumber/runtime/support_code.rb
- lib/cucumber/step_match.rb
- lib/cucumber/step_match_search.rb
- spec/cucumber/formatter/legacy_api/adapter_spec.rb
> fix Lint/UnusedArgument

- .travis.yml
Travis build is failing due to this bug: https://github.com/sickill/rainbow/issues/49.
Running `gem update --system` before running `bundle install` fixes the problem (see https://github.com/sickill/rainbow/issues/49#issuecomment-274714272 and https://github.com/bundler/bundler/issues/5357#issuecomment-274742137)
> Run rubygems update before installing

- .rubocop_todo.yml
- features/docs/api/listen_for_events.feature
- features/docs/events/step_activated_event.feature
- features/docs/events/step_definition_registered_event.feature
- features/docs/events/test_case_finished_event.feature
- features/docs/events/test_case_starting_event.feature
- features/docs/events/test_run_finished_event.feature
- features/docs/events/test_step_finished_event.feature
- features/docs/events/test_step_started_event.feature
- features/docs/events/test_step_starting_event.feature
- lib/cucumber/configuration.rb
- lib/cucumber/events.rb
- lib/cucumber/events/step_activated.rb
- lib/cucumber/events/step_definition_registered.rb
- lib/cucumber/events/test_case_finished.rb
- lib/cucumber/events/test_case_starting.rb
- lib/cucumber/events/test_step_finished.rb
- lib/cucumber/events/test_step_starting.rb
- lib/cucumber/filters/activate_steps.rb
- lib/cucumber/formatter/legacy_api/adapter.rb
- lib/cucumber/formatter/progress.rb
- lib/cucumber/formatter/usage.rb
- lib/cucumber/rb_support/rb_step_definition.rb
- lib/cucumber/runtime/support_code.rb
- spec/cucumber/filters/activate_steps_spec.rb
Improve documentation for the Events API
This change wraps each of the test case/step starting/finished events that are emitted from `cucumber-core` with event types defined in the `Cucumber::Events` namespace.
It also adds a feature file / acceptance test describing each event.
The events API is the most important part of Cucumber's API, and needs to be well documented. This will help people writing future plug-ins and extensions, as well as those migrating their formatters off of the old API once we deprecate it.
Since we moved main before/after test case/step events into the core, the YARD API docs have got worse, because those events have disappeared from the `Cucumber::Events` namespace. This change wraps the events in core with subclasses in `Cucumber::Events` so that all of the …
> Document events

- cucumber.gemspec
Fix an json compile error for "bundle install" on Ruby 2.4.
Installed json-1.8.3 does not have a compatibility for Ruby 2.4.
```
$ ruby -v
ruby 2.4.0p0 (2016-12-24 revision 57164) [x86_64-linux]
```
```
$ bundle -v
Bundler version 1.13.7
```
On lastest master branch (commit hash: 8871da436987e2c46623a24909a925818be52314)
```
$ pushd ../cucumber-ruby-core
$ git checkout v2.0.0
$ popd
```
```
$ pushd ../cucumber-ruby-wire
$ git checkout v0.0.1
$ popd
```
```
$ bundle install --path vendor/bundle
...
current directory:
/home/jaruga/git/cucumber-ruby/vendor/bundle/ruby/2.4.0/gems/json-1.8.3/ext/json/ext/generator
/usr/local/ruby-2.4.0/bin/ruby -r ./siteconf20170109-6691-15ef87j.rb extconf.rb
creating Makefile
current directory:
/home/jaruga/git/cucumber-ruby/vendor/bundle/ruby/2.4.0/gems/json- …
```
> Fix an json compile error for "bundle install" on Ruby 2.4.

- .travis.yml
Add Ruby 2.4.0 as allow_failures in .travis.yml because of seeing tests failure situation on Ruby 2.4.0.
It is good to merge Ruby 2.4.0 features one by one seeing the result of Travis.
I might be better to merge this PR at first earlier than #1077.
> Add Ruby 2.4.0 as allow_failures in .travis.yml

- lib/cucumber/formatter/backtrace_filter.rb
This fixes tests with /usr/local/ruby-X.Y.Z/bin/bundle.
The solution is mentioned by https://github.com/cucumber/cucumber-ruby/pull/1069#issuecomment-278132114
Can you check this PR before #1077 ?
Want to pass tests.
There is still an error. but it is another reason.
```
$ ruby -v
ruby 2.4.0p0 (2016-12-24 revision 57164) [x86_64-linux]
$ bundle -v
Bundler version 1.14.3
$ bundle exec rake spec
...
568 examples, 0 failures
$ bundle exec rake cucumber
...
(::) failed steps (::)
expected "No such file or directory @ rb_sysopen - features. You can use `cucumber --init` to get started.\n" to include "No such file or directory - features. You can use `cucumber --init` to get started."
Diff:
@@ -1,2 +1,2 @@
-No such file or directory - features. You can use `cucumber --init` to get started.
+No …
```
> Relax filter for "/usr/local/ruby-X.Y.Z/bin/bundle".

- cucumber.yml
- features/docs/cli/execute_with_tag_filter.feature
- features/docs/writing_support_code/tagged_hooks.feature
- features/lib/support/env.rb
- lib/cucumber/cli/configuration.rb
- lib/cucumber/cli/options.rb
- lib/cucumber/configuration.rb
- lib/cucumber/rb_support/rb_hook.rb
- spec/cucumber/cli/configuration_spec.rb
- spec/cucumber/cli/options_spec.rb
Support [standard library tag expressions](https://github.com/cucumber/cucumber/tree/master/tag-expressions) from the cucumber-tag_expressions gem.
The tag limits from the `--tags` options are stripped of and handled separately, so that the stored tag expressions can be passed the tag expressions library directly.
Old style tag expressions are deprecated but still handled correctly.
Requires https://github.com/cucumber/cucumber-ruby-core/pull/116
Closes https://github.com/cucumber/cucumber-ruby/issues/1003
Features and spec are updated accordingly.
> Use tag expressions from the cucumber-tag_expressions gem.

- lib/cucumber/runtime.rb
This fixes #1071.
This issue happens for only Ruby 2.4.0.
Want to pass tests.
```
$ ruby -v
ruby 2.4.0p0 (2016-12-24 revision 57164) [x86_64-linux]
$ bundle exec rake spec
...
568 examples, 0 failures
$ bundle exec rake cucumber
...
207 scenarios (17 failed, 190 passed)
1217 steps (17 failed, 1200 passed)
```
There are still failed tests. But they will be fixed by https://github.com/cucumber/cucumber-ruby/pull/1079 .
The `rb_sysopen` message was disappeared.
> Avoid showing "@ rb_sysopen" noise for Ruby 2.4.

- .travis.yml
Change Ruby 2.4.0 from allow failures to required.
I changed Ruby 2.4.0 from allow failures to required.
Because this looks better than current "allow_failures".
We can skip Ruby 2.4's coverage until `coveralls` supports `simplecov` (>= 0.13.0) as a dependency package for Ruby 2.4 compatibility.
https://rubygems.org/gems/coveralls
I added "ruby-head" as a "allow_failures".
I think this is useful, because we can prepare `cucumber` for next Ruby version 2.5 in advance before it will be released.
Adding "ruby-head" as a "allow_failures" is actually practiced by `rspec` and  `rails`.
And this is the secret that they could support Ruby 2.4.0 quickly.
So, I want to add it to `cucumber` too.
https://github.com/rspec/rspec-core/blob/master/.travis.yml …
> Add ruby-head as a allow failures in .travis.yml.

- .rubocop_todo.yml
- features/lib/step_definitions/language_steps.rb
- features/lib/support/normalise_output.rb
- lib/autotest/cucumber_mixin.rb
- lib/cucumber/events.rb
- lib/cucumber/formatter/html.rb
- lib/cucumber/formatter/junit.rb
- lib/cucumber/formatter/legacy_api/adapter.rb
- lib/cucumber/formatter/legacy_api/ast.rb
- lib/cucumber/formatter/pretty.rb
- lib/cucumber/multiline_argument/data_table.rb
- lib/cucumber/step_match_search.rb
- spec/cucumber/cli/options_spec.rb
- spec/cucumber/formatter/html_spec.rb
- spec/cucumber/formatter/json_spec.rb
- spec/cucumber/multiline_argument/data_table_spec.rb
- spec/cucumber/running_test_case_spec.rb
Several fixes has been made for some of the RuboCop offenses reported.
The following style violations has been fixed whether completely or partially:
- Style/TrailingCommaInArguments
- Style/TrivialAccessors
- Style/UnlessElse
- Style/UnneededInterpolation
- Style/UnneededInterpolation
- Style/WhileUntilDo
- Style/WordArray
- Style/ZeroLengthPredicate
There are RoboCop's offenses reviewed but not fixed due to irrelevance like `Style/VariableName` for the Cyrillic variable names.
There is bunch of exceptions for the code styling tool of RoboCop to be fixed.
Here is the main issue: #1021 
Although only styling is being changed, there is setup of [Travis ](https://travis-ci.org/bv/cucumber-ruby/builds/210334869) to run the proper set of tests. All the tests are green (except for the allowed …
> Fix some rubocop offenses 1021 001

- lib/cucumber/multiline_argument/data_table.rb
- spec/cucumber/multiline_argument/data_table_spec.rb
Fixes the following:
```ruby
DataTable.from([[]]).diff! [[]] #=> NoMethodError: undefined method `length' for nil:NilClass
```
See #1096 for much more details.
Added a private `#ensure_2d` method to DataTable, and used it internally in `#pad_and_match` to make sure we're always dealing with an array of arrays, which the code had previously been assuming.
Fixes #1096
Added unit test to expose bug, then wrote patch to fix it.
> Fix diffing empty DataTables

- README.md
Add supported platforms to README.
This clarify `cucumber-ruby` and other `cucumber` ruby projects' policy used with `cucumber-ruby`.
Here is updated README.md
https://github.com/junaruga/cucumber-ruby/blob/feature/readme-supported_platforms/README.md
I also replaced a wield character code on the left of "Code of Conduct" in `README.md` to white space.
This PR is from below `cucumber-ruby-wire` PR not to get lost supported platforms.
https://github.com/cucumber/cucumber-ruby-wire/commit/77d1f70b7c2576aeda15dd9dc06773c897290625#commitcomment-21260194
No test. as it updates document.
> Add supported platforms to README.md.

- .travis.yml
Remove Ruby 2.4 from allow_failures in .travis.yml.
Because coveralls 0.8.20 for Ruby 2.4 compatibility was released today.
We want to check Ruby 2.4 on Travis.
See also https://github.com/lemurheavy/coveralls-ruby/pull/117
Travis will test it.
> Remove Ruby 2.4 from allow_failures in .travis.yml.

- lib/cucumber/multiline_argument/data_table.rb
- spec/cucumber/multiline_argument/data_table_spec.rb
This fixes a bug in `#diff!` that was causing incorrect values to be displayed for the header row in the diff report.
If columns were missing in the first table, they would be filled in with instances of `SurplusCell`. However, the same instance of `SurplusCell` was being used for every missing column in the header column, so when the value was being set on one cell, it was being set on them all. This led to the last value "winning," and the diff report reporting an incorrect diff summary. For example:
```ruby
DataTable.from([[]]).diff! DataTable.from(%{
|a|b|c|
|d|e|f|
|g|h|i|
})
| (+) c | (+) c | (+) c |
| (+) d | (+) e | (+) f |
| (+) g | (+) h | (+) i |
```
The fix is simply to generate a new instance of SurplusCell for each cell.
Added two tests to expose the bug, and added the patch …
> Fix incorrect DataTable#diff! report

- History.md
Render markdown in the changelog correctly, by replacing a non-space character with a space.
> History: change bad character to space

- .rubocop_todo.yml
- lib/cucumber/cli/options.rb
- lib/cucumber/multiline_argument/data_table.rb
- lib/cucumber/term/ansicolor.rb
- spec/cucumber/file_specs_spec.rb
- spec/cucumber/filters/tag_limits/verifier_spec.rb
- spec/cucumber/formatter/legacy_api/adapter_spec.rb
- spec/cucumber/rb_support/rb_step_definition_spec.rb
Several fixes have been made for some of the RuboCop offenses reported.
There are rubocop offenses, which has been fixed:
Style/TrailingCommaInLiteral
Style/SpaceBeforeFirstArg
Style/ParenthesesAroundCondition
There is bunch of exceptions for the code styling tool of RoboCop to be fixed.
Here is the main issue: #1021 
`bundle exec rake` produces no test failures
There build configuration on Travis passes green: https://travis-ci.org/bv/cucumber-ruby-bv/builds/218226436
> Fix rubocop offenses 1021 003

- features/docs/events/gherkin_source_read_event.feature
- lib/cucumber/events.rb
- lib/cucumber/events/gherkin_source_read.rb
- lib/cucumber/runtime.rb
Adds a new event that fires when a Gherkin document is read in.
This event will allow formatters to create their own Gherkin AST, should they need it. This would also potentially allow us to simplify the core `Test::Case` value objects to no longer contain references to the AST.
It's also needed to support the standard [event protocol](https://github.com/cucumber/cucumber/tree/master/event-protocol)
See `features/docs/events/gherkin_source_read_event.feature`
> Add a `GherkinSourceRead` event

- .travis.yml
This PR updates the CI matrix to use latest JRuby.
> Travis: use jruby-9.1.10.0

- features/docs/events/test_case_starting_event.feature
This PR verifies that both feature- and scenario-level tags are available inside test_case_starting event hooks
See cucumber/cucumber-ruby-core#115 for context.
Since the required functionality already works in the new events API, this PR only changes a feature to make sure the functionality is tested.
There was a concern that feature-level tags were not available in before_tag hooks in the old formatter API. This PR verifies that this is fixed in the new events API
Made an addition to one of the feature files.
> Test that tags are available in the before_test_case event

- lib/cucumber/runtime.rb
When the events are queued in the event queue (https://github.com/cucumber/cucumber-ruby-core/pull/136) and passed to new handlers when they register, there is no need to delay the loading
of the step definitions until the formatter have been created.
This reverts change of cc7eb89 in runtime.rb (from #977).
> Do not delay the the loading of step definitions

- .rubocop.yml
This PR enables displaying RuboCop **cop names** and **styleguide URLs** for each failed cop.
To help people trying to fix or disable cop warnings, the name and URL helps.
We are currently on RuboCop 0.40.0, and [these are that version's configuration option defaults](https://github.com/bbatsov/rubocop/blob/v0.40.0/config/default.yml).
I saw someone struggling with cop output. The tool ought to present all it knows.
Here is a picture with some failures that I added to one file. 
In practice, this is what it looks like **with extra information:**
Contrast this with the before **without extra information:**
> RuboCop setting: add name of failed cop rule; URL

- cucumber.gemspec
- scripts/update-history
As discussed at CukenFest, this will avoid manual error when updating
history. It still needs to be run manually, and requires that one of the
`type: *` labels has been applied to the PR.
It's still going to save me time!
> Add script to update history.md

- features/docs/cli/i18n.feature
- lib/cucumber/cli/options.rb
- spec/cucumber/cli/options_spec.rb
Emulates Cucumber-JS's new i18n CLI options.
Fixes https://github.com/cucumber/cucumber-ruby/issues/1137 and fixes a test.
See issue https://github.com/cucumber/cucumber-ruby/issues/1137
Keeping things consistent between implementations.
Existing tests have been modified to meet the new requirements.
Please review @mattwynne @tooky
> Emulate Cucumber-JS's new i18n CLI options

- .rubocop_todo.yml
- lib/cucumber/cli/profile_loader.rb
- spec/cucumber/cli/profile_loader_spec.rb
Fixed a profile parsing bug that was only affecting Windows.
A bug in the profile loader was discovered while working on #1116. This PR fixes that bug.
Bug fix + tests. Rather than try to re-implement the parsing being done by Shellwords, I simply _temporarily_ adjusted the input data so that Shellwords could handle it as usual.
The problem was discovered during #1116 but it was decided to handle it separately rather than making it a blocking problem on that PR.
New spec added for the profile loader.
> Fixing the profile loader

- cucumber.yml
This PR updates the Cucumber YAML file to use the new tag syntax, such as `"not @wire"` instead of the old syntax `~@wire`.
This change will remove deprecation warnings that are currently appearing in CI.
> Update cucumber yaml to use new tag syntax

- .rubocop_todo.yml
- lib/cucumber/cli/options.rb
- lib/cucumber/core_ext/instance_exec.rb
- lib/cucumber/glue/dsl.rb
- lib/cucumber/glue/hook.rb
- lib/cucumber/glue/invoke_in_world.rb
- lib/cucumber/glue/proto_world.rb
- lib/cucumber/glue/registry_and_more.rb
- lib/cucumber/glue/snippet.rb
- lib/cucumber/glue/step_definition.rb
- lib/cucumber/glue/transform.rb
- lib/cucumber/glue/world_factory.rb
- lib/cucumber/rb_support/rb_language.rb
- lib/cucumber/runtime.rb
- lib/cucumber/runtime/for_programming_languages.rb
- lib/cucumber/runtime/support_code.rb
- lib/cucumber/runtime/user_interface.rb
- lib/cucumber/step_definition_light.rb
- spec/cucumber/formatter/html_spec.rb
- spec/cucumber/formatter/spec_helper.rb
- spec/cucumber/glue/proto_world_spec.rb
- spec/cucumber/glue/registry_and_more_spec.rb
- spec/cucumber/glue/snippet_spec.rb
- spec/cucumber/glue/step_definition_spec.rb
- spec/cucumber/glue/transform_spec.rb
- spec/cucumber/runtime/for_programming_languages_spec.rb
- spec/cucumber/step_match_search_spec.rb
- spec/cucumber/step_match_spec.rb
- spec/cucumber/world/pending_spec.rb
The old programming language abstraction is confusing. This starts to improve the names and lay the groundwork to get rid of all the mess it hides.
There's lots of global state and mutation that we can clean up.
> Remove programming language abstraction

- spec/cucumber/events_spec.rb
This PR adds a unit test which calls the method `Events.registry`, in order to exercise the code. See #1124 
---
Eh, also: work to get rid of all the Ruby warnings, to prepare to enable `--warnings` in `.rspec`.
> Spec: Events.registry exercised

- gem_tasks/contributors.rake
This PR works around an encoding issue in `rake contributors`.
Without this workaround, the output is:
```
rake aborted!
ArgumentError: invalid byte sequence in UTF-8
gem_tasks/contributors.rake:6:in `split'
gem_tasks/contributors.rake:6:in `block in <top (required)>'
```
The solution propsed (to allow the Rake task to run without error) is to run the `git` command pipeline in a `IO.popen`, which is also supported on Windows.
Wrong fixes tried:
- I first used the same `iconv` transform from latin1 to utf8 used in the same file to transform the Git log output with the contributor names. That's quite bad since many contributors' names have characters which would be mangled by that transform.
- The other wrong fix is to run the command using Open3.popen3. Non-Windows.
The change allows the …
> Rake task: list contributors encoding workaround

- .rubocop_todo.yml
- features/lib/step_definitions/wire_steps.rb
- features/lib/support/fake_wire_server.rb
- lib/cucumber/glue/transform.rb
- lib/cucumber/runtime/support_code.rb
- spec/cucumber/formatter/spec_helper.rb
This PR fixes the AssignmentInCondition violations currently being ignored by Rubocop and configures Rubocop not to ignore these files.
Separated variable assignments from conditionals/loop conditions.
> Fix AssignmentInCondition violations in Rubocop

- features/docs/cli/dry_run.feature
- features/docs/cli/strict_mode.feature
- lib/cucumber/formatter/console_counts.rb
- lib/cucumber/formatter/console_issues.rb
- lib/cucumber/runtime.rb
List all not ok scenarios in the summary.
Currently only failed scenarios are listed in the summary, but also scenarios of other result types can force the exit code to be non-zero (currently `pending` and `undefined` scenarios - in strict mode). Therefore list the scenarios of all result type the each would have made the exit code non-zero.
Also reduce the duplication between Cucumber-Ruby and Cucumber-Ruby-Core by using
* `Cucumber::Core::Report::Summary#ok?` to calculate the exit code
* `Cucumber::Core::Test::Result::TYPES` and `Cucumber::Core::Report::Summary` in `ConsoleCounts`
These changes also paves the way for the introduction of [`ambiguous` results](https://github.com/cucumber/cucumber-ruby/pull/1132) and [`flaky` results](https://github.com/cucumber/cucumber-ruby/pull/1121#issu …
> List all not ok scenarios in the summary

- .rubocop_todo.yml
- lib/cucumber/formatter/legacy_api/ast.rb
This PR fixes Rubocop violations in the `legacy_api/ast.rb` file and configures Rubocop not to ignore this file.
Removed `legacy_api/ast.rb` from the .rubocop-todo.yml file. Fixed violations in the file by enclosing arguments to two method calls in parens.
> Fix Rubocop violations in Legacy API AST file

- features/docs/cli/retry_failing_tests.feature
- lib/cucumber/formatter/ansicolor.rb
- lib/cucumber/formatter/console_issues.rb
Detect and list flaky scenarios in the list of not ok scenarios
* Detect and list flaky scenarios in the list of not ok scenarios
* Add a colour definition for `flaky` results.
* Also updated the retry feature for the separation of flaky scenarios to a separate category in the scenario counts.
Depends on https://github.com/cucumber/cucumber-ruby-core/pull/141.
This is needed to complete the introduction of the `flaky` result type in https://github.com/cucumber/cucumber-ruby-core/pull/141.
The retry feature has been updated to verify this behaviour.
> Detect and list flaky scenarios in the list of not ok scenarios

- features/docs/defining_steps/ambiguous_steps.feature
- lib/cucumber/filters/activate_steps.rb
- lib/cucumber/step_match.rb
Added scenario about how the reporting of ambiguous step match should be. See #1113 
Spike of an example we think reporting could be.
Fixes #1113
> Adds scenario for the ambiguous step reporting

- lib/cucumber/cli/configuration.rb
- lib/cucumber/cli/options.rb
- lib/cucumber/configuration.rb
- lib/cucumber/formatter/console_issues.rb
- lib/cucumber/formatter/fail_fast.rb
- lib/cucumber/formatter/junit.rb
- lib/cucumber/formatter/legacy_api/adapter.rb
- lib/cucumber/formatter/rerun.rb
- lib/cucumber/runtime.rb
- spec/cucumber/cli/configuration_spec.rb
- spec/cucumber/formatter/fail_fast_spec.rb
- spec/cucumber/formatter/legacy_api/adapter_spec.rb
Let the result types affected the the strict settings be controlled individually, so only a subset of the can be set to be handled strict.
Add the options 
* `--[no-]strict-undefined`, 
* `--[no-]strict-pending`, and
* `--[no-]strict-flaky`, 
so each of the result type affected by the strict settings be controlled individually. 
The `--[no-]strict` option is equivalent to `--[no-]strict-undefined --[no-]strict-pending --[no-]strict-flaky`. 
Also make sure that it is possible from the command line to adjust the strict setting from a profile, for instance:
Given that a profile includes the `--strict` option
When using `--no-strict-flaky` on the command line
Then only `undefined` and `pending` will be handled strict
Depends on cucumber/cucumber-core#143.
Fixes #1160.
The automated test suite …
> Handle selective strict options.

- .rubocop_todo.yml
- lib/cucumber/project_initializer.rb
Fix Lint/DeprecatedClassMethods
* Offense count: 1
> Fix Lint/DeprecatedClassMethods

- .rubocop_todo.yml
- lib/cucumber/cli/profile_loader.rb
- lib/cucumber/deprecate.rb
- lib/cucumber/formatter/html.rb
- lib/cucumber/formatter/legacy_api/adapter.rb
- lib/cucumber/formatter/legacy_api/ast.rb
- lib/cucumber/hooks.rb
- lib/cucumber/multiline_argument/data_table.rb
- lib/cucumber/runtime/user_interface.rb
- spec/cucumber/cli/options_spec.rb
- spec/cucumber/world/pending_spec.rb
Fixing multiple, low offense count, cops.
* Offenses:
* Style/ClassCheck: 3
* Style/ClosingParenthesisIndentation: 1
* Style/ColonMethodCall: 1
* Style/CommentAnnotation: 1
* Style/CommentIndentation: 2
* Style/ConditionalAssignment: 1
* Style/ConstantName: 1
> Fix Multiple Cops

- .rubocop_todo.yml
- lib/cucumber/cli/options.rb
- lib/cucumber/rake/task.rb
- spec/cucumber/formatter/legacy_api/adapter_spec.rb
- spec/cucumber/multiline_argument/data_table_spec.rb
- spec/cucumber/rake/forked_spec.rb
Partially Fixing Metrics/AlignArray
* All offending directories except 'spec/cucumber/formatter/legacy_api/adapter_spec.rb' which has 1106 offenses
> Fix Style/AlignArray

- bin/cucumber
Partially Fixing Metrics/LineLength
* Changed only offending file in bin
* Unsure if this solution would be an acceptable one, but all tests pass. Can change as needed.
> Fix Metrics/LineLength - PARTIAL - 02

- features/lib/step_definitions/iso-8859-1_steps.rb
- features/lib/support/fake_wire_server.rb
Partially Fixing Metrics/LineLength
* Fixing features directory
* Offenses: 3
> Fix Metrics/LineLength - PARTIAL - 03

- .rubocop_todo.yml
- lib/cucumber/multiline_argument.rb
- lib/cucumber/runtime/support_code.rb
Investigated the Lint/DuplicateMethods offenses and need guidance on how best to address them.
* Offense count: 2
* Added review note as I'm unsure how these should be handled.
* Review note: In the two instances of duplication, both methods are under MultilineArgument, but one self method calls another that belongs to the private Builder class.
* [Here's the code in question](https://github.com/jaysonesmith/cucumber-ruby/blob/1021-fix-style-violations-2/lib/cucumber/multiline_argument.rb#L31*L58)
> Fix Lint/DuplicateMethods

- History.md
History.md update.
* 6 PRs
* They're in numerical order too!
We need to keep track of what's changed!
Code change is only to a .md file, but `bundle exec rake` is 👍
> History.md Update

- .gitattributes
- gem_tasks/fix_cr_lf.rake
This PR changes the `fix_cr_lf` Rake task: it now fixes CRLF **on the right files**.
The previous exclusion rules were for files with `dos` in the filename – these files are no longer a part of the codebase.
Also: tell Git how to clone files using the [Dealing with line endings](https://help.github.com/articles/dealing-with-line-endings/) documentation that GitHub wrote.
> Rake task fix_cr_lf: exclude iso-8859-1 files

- CHANGELOG.md
CHANGELOG.md updates as per [cucumber/cucumber #251](https://github.com/cucumber/cucumber/issues/251)
* Renamed History.md to CHANGELOG.md (did this directly against master in some dopey attempts at fixing something that wasn't broken.)
* Changed category names
* Added contributing message at top
> CHANGELOG updates for monorepo's #251

- lib/cucumber/formatter/html.rb
- lib/cucumber/formatter/html_builder.rb
- spec/cucumber/formatter/html_spec.rb
This PR builds on #1138, DRYing up some code in the `Formatter::HTMLBuilder` class in response to CodeClimate analysis.
I extracted the `Formatter::HTMLBuilder#string_to_embed` private method to deduplicate code in the `Formatter::HTMLBuilder#embed_string` and `Formatter::HTMLBuilder#embed_image` methods. These methods have been combined into a single `Formatter::HTMLBuilder#embed` method, which is called from the HTML formatter class.
After #1138 got merged, I saw that the class still had a low rating in CodeClimate. I wanted to keep quality high, at least for my own code, so I made some of the changes CodeClimate suggested.
Since this is a refactor, it didn't require additional tests. I just made sure that the existing tests passed.
- ~~[ ] I've added tests for my code~~
- ~~[ ] My …
> Extract HTMLBuilder#string_to_embed method to DRY up code

- lib/cucumber/multiline_argument/data_table.rb
- spec/cucumber/multiline_argument/data_table_spec.rb
DataTable#symbolic_hashes will no longer set the instance variable `@header_conversion_proc` but instead will act in a similar manner to DataTable#hashes except returning a new array of hashes with symbolic keys.
Changed DataTable#symbolic_hashes to call DataTable#hashes and then map the return value to a new hash with all keys changed to symbols using the method DataTable#symbolize_key(key).
Solves the issue reported here #1199 
Added the following test: `spec/cucumber/multiline_argument/data_table_spec.rb`.  This is intended to ensure that after using DataTable#symbolic_hashes, no error is raised when using DataTable#hashes (see issue: #1199 )
The test only been run in the following environments so far:
- Ruby 2.3.0 using `bundle exec rake`
> Fix for issue: #1199: Changed DataTable#symbolic_hashes to not change the state of the table

- lib/cucumber/formatter/io.rb
- spec/cucumber/formatter/junit_spec.rb
I hit an issue that sometimes after failure the junit reports cannot be 
generated due to:
```
No such file or directory @ rb_sysopen - junit-report/TEST-features-admin-build.xml (Errno::ENOENT)
```
I initially asked about this in:
https://groups.google.com/forum/#!topic/cukes/EZ9mOm7iiKs
> use absolute path to avoid chdir issues

- CHANGELOG.md
- features/docs/writing_support_code/parameter_types.feature
- lib/cucumber/glue/dsl.rb
- lib/cucumber/glue/proto_world.rb
As I've argued in https://github.com/cucumber/cucumber-ruby/issues/1190 we should remove `Transform` rather than deprecating it. My position is that deprecated functionality should satisfy all of the following:
* work as before deprecation
* provide users with an alternative API in the same version
* no longer issue warnings when the alternative API is used
We can't do all of these in a 2.x release, so we should remove in 3.0, and not deprecate in 2.x.
> Remove Transform

- features/docs/api/listen_for_events.feature
- features/docs/events/test_step_finished_event.feature
- lib/cucumber/filters/activate_steps.rb
- lib/cucumber/formatter/console.rb
- lib/cucumber/formatter/json.rb
- lib/cucumber/formatter/junit.rb
- lib/cucumber/formatter/legacy_api/adapter.rb
- lib/cucumber/formatter/legacy_api/ast.rb
- lib/cucumber/hooks.rb
- spec/cucumber/filters/activate_steps_spec.rb
- spec/cucumber/formatter/json_spec.rb
- spec/cucumber/formatter/junit_spec.rb
- spec/cucumber/hooks_spec.rb
- spec/support/standard_step_actions.rb
This PR is a follow-up to (the now-merged) https://github.com/cucumber/cucumber-ruby-core/pull/137 
It
> Step: Rename name to text

- .circleci/config.yml
- .gitignore
- Gemfile
- Gemfile.lock
- README.md
- cucumber.gemspec
The travis build currently takes over 40 minutes to give us feedback.
I set up [CircleCI](https://circleci.com/gh/cucumber/cucumber-ruby) and feedback time is now down to a couple of minutes.
As part of doing this I also simplified the `Gemfile` (changed the mechanism for using local dependencies).
The `Gemfile.lock` is now checked in, which allows CircleCI to cache gems and speed up the build. It's excluded from the built gem.
The `cucumber.gemspec` no longer runs git to list all files. The jruby docker image doesn't have git, and we shouldn't assume anyone has git. Not running git is also faster.
> CircleCI build

- spec/cucumber/cli/configuration_spec.rb
Paraphrasing @enkessler who helped me pin down what was going on here (thanks!): Ruby doesn't guarantee the sort order of `sort` or `sort_by` if the objects have the same comparison value.
Unfortunately, the test data we were using falls under the scenario above and it was causing a couple tests to fail on my machine. `[['progress', {}, 'file1'], ['profile', {}, 'file2']]` was going through a sort_by that should not have changed the output order of the arrays, but instead the following was being returned: `[['profile', {}, 'file2'], ['progress', {}, 'file1']]`
Instead of using rspec's `eq` check, I've changed the tests to use `match_array.`
Fixing this primarily to allow me to dev on my Windows machine at home, but could also be extended to helping prevent this type of error from …
> Change test expectation to handle Ruby's unstable sorting

- .rubocop.yml
~This PR changes the Travis CI configuration to:~
- ~**skip** `gem update --system`. This is now done by the `rvm` package manager, built-in.~
- ~cache bundler~
- **skip** vendor directories in `rubocop` (now that they're cached)
The goal is: quicker builds.
~Travis is~ now 💚
> RuboCop: skip vendor directory

- lib/cucumber/formatter/html.rb
- spec/cucumber/formatter/html_spec.rb
There was typo in `#next_id` method: `@indices` used incorrect key for incrementing screenshot number (_:type_ as a symbol instead of _type_ as a variable). It was lead to confusion when every screenshot in reporter pointed to the same image id.
`formatter/html_spec.rb` has been extended to cover a case with more than one screenshot in html-report.
> Fix html reporter with more than one embedded screenshot

- cucumber.yml
- lib/cucumber/term/ansicolor.rb
The pragma comment doesn't pick up these uses because the code is eval'd on the fly.
Related:
* https://github.com/dblock/syntax/pull/6
* https://github.com/cucumber/aruba/pull/436
* https://github.com/rspec/rspec-core/pull/2437
I've managed to get the test suite passing locally with the `--enable-frozen-string-literal` `RUBYOPT` flag, using my own copy of Aruba plus some related upgrading changes because Cucumber's been locked to an old Aruba version for quite some time. I've also used the rspec-core test suite (which makes use of Cucumber) and my local cucumber copy to confirm their test suite is green as well.
Given the pragma comments, I'm presuming being frozen-string-literal-friendly is a goal of Cucumber, hence pretty confident in labelling this a bug fix :)
None of the checklist …
> Frozen-string-literal fixes in eval'd code.

- .rubocop_todo.yml
- CHANGELOG.md
- lib/cucumber/multiline_argument/data_table/diff_matrices.rb
- Simple visibility change
- Fixed with the auto flag
> Fix Layout/EmptyLineBetweenDefs

- .rubocop_todo.yml
- CHANGELOG.md
- examples/test_unit/Gemfile
- Gemfile alphabetical ordering
> Fix Bundler/OrderedGems

- lib/cucumber/formatter/interceptor.rb
- lib/cucumber/formatter/junit.rb
- spec/cucumber/formatter/interceptor_spec.rb
- spec/cucumber/formatter/junit_spec.rb
Fix  incompatible character encodings error in Junit formatter which occurs if strings with incompatible encodings were written to pipe.
Replaced array buffer in Interceptor::Pipe with StringIO to prevent  incompatible character encodings error. This also elements need to join array in Junit formatter and reduces exposure of internals of pipe interceptor. Although #buffer method was kept and is backward compatible in case any end user code is using it.
This fixes issues of cucumber failing to generate junit report for test cases that had non UTF strings in different languages logged during test run.
Add test case for junit formatter to write output in case of incompatible strings being logged during test run.
> Fix incompatible encodings error in Junit formatter

- .circleci/config.yml
- .rubocop.yml
- .rubocop_todo.yml
- CHANGELOG.md
- cucumber.gemspec
- lib/cucumber/formatter/interceptor.rb
- Rubocop likes the ruby version specified to be the same between .rubocop.yml and the required version in the gemspec. Since we hadn't specified a version in the rubocop file, it defaulted to the 2.1 which doesn't equal 2.2. :)
Update the versions and the comments for each. Also had a Lint/UnneededRequireStatement violation pop up that I handled.
> Fix Gemspec/RequiredRubyVersion

- .rubocop_todo.yml
- CHANGELOG.md
- cucumber.gemspec
- Alphabetize dependencies in gemspec
> Fix Ordered/Dependencies

- .rubocop_todo.yml
- CHANGELOG.md
- spec/cucumber/step_match_search_spec.rb
- Looks like in the attempt at keeping line length shorter, a new line was used which Rubocop doesn't like.
> Fix Layout/BlockEndNewline

- .rubocop_todo.yml
- CHANGELOG.md
- lib/cucumber/constantize.rb
- lib/cucumber/filters/randomizer.rb
- scripts/invite-collaborator
- spec/cucumber/multiline_argument/data_table_spec.rb
- This cop supports leading OR trailing dots for chained lines.
> Fix Layout/DotPosition

- .rubocop.yml
- CHANGELOG.md
- Rakefile
- lib/cucumber/formatter/interceptor.rb
- spec/cucumber/formatter/junit_spec.rb
- Added Rubocop to the default Rake task 
- This way folks contributing to the project are forced to follow the style guidelines we're moving toward and don't add new violations that need to be fixed.
Working to help solve issue [1021](https://github.com/cucumber/cucumber-ruby/issues/1021) and keep it solved!
> Add Rubocop to default Rake task

- .rubocop_todo.yml
- CHANGELOG.md
- lib/cucumber/cli/main.rb
- lib/cucumber/events/step_definition_registered.rb
- lib/cucumber/formatter/backtrace_filter.rb
- lib/cucumber/formatter/interceptor.rb
- lib/cucumber/multiline_argument/data_table.rb
- lib/cucumber/runtime/step_hooks.rb
- lib/cucumber/step_match.rb
- lib/cucumber/term/ansicolor.rb
- scripts/invite-collaborator
- spec/cucumber/formatter/junit_spec.rb
- spec/cucumber/runtime/support_code_spec.rb
Fixed the following simple cops:
- Layout/EmptyLines
- Layout/EmptyLinesAroundAccessModifier
- Layout/EmptyLinesAroundArguments
- Layout/EmptyLinesAroundExceptionHandlingKeywords
> Fix: Layout/EmptyLines, ...AroundAccessModifier, ...AroundArguments, ...AroundExceptionHandlingKeywords

- .rubocop_todo.yml
- CHANGELOG.md
- features/lib/support/fake_wire_server.rb
- lib/cucumber/cli/options.rb
- lib/cucumber/formatter/ansicolor.rb
- lib/cucumber/gherkin/formatter/ansi_escapes.rb
- spec/cucumber/glue/step_definition_spec.rb
- spec/cucumber/multiline_argument/data_table_spec.rb
- spec/cucumber/rake/forked_spec.rb
> Fix Layout/IndentArray & Layout/IndentHash

- .rubocop_todo.yml
- CHANGELOG.md
- lib/cucumber/cli/main.rb
- lib/cucumber/cli/options.rb
- lib/cucumber/filters/broadcast_test_run_started_event.rb
- lib/cucumber/filters/quit.rb
- lib/cucumber/filters/randomizer.rb
- lib/cucumber/filters/tag_limits.rb
- lib/cucumber/formatter/html.rb
- lib/cucumber/formatter/html_builder.rb
- lib/cucumber/formatter/interceptor.rb
- lib/cucumber/glue/proto_world.rb
- lib/cucumber/multiline_argument.rb
- lib/cucumber/multiline_argument/data_table.rb
- lib/cucumber/platform.rb
- lib/cucumber/rake/task.rb
- lib/cucumber/runtime.rb
- lib/cucumber/runtime/support_code.rb
- lib/cucumber/runtime/user_interface.rb
- spec/cucumber/cli/profile_loader_spec.rb
- The [space between](http://www.metrolyrics.com/the-space-between-lyrics-dave-matthews-band.html) things is to be updated.
> Fix Layout/SpaceAroundEqualsInParameterDefault & Layout/SpaceAroundKeyword

- .rubocop.yml
- .rubocop_todo.yml
- CHANGELOG.md
- lib/cucumber/cli/options.rb
- lib/cucumber/formatter/junit.rb
- lib/cucumber/runtime.rb
- scripts/invite-collaborator
- spec/cucumber/configuration_spec.rb
- spec/cucumber/formatter/spec_helper.rb
- Layout/MultilineArrayBraceLayout
- Layout/MultilineBlockLayout
- Layout/MultilineMethodCallBraceLayout
- Layout/MultilineMethodCallIndentation
- Layout/MultilineOperationIndentation
- Metrics/ClassLength exclusion for the CLI's options also.
> Fix Multiline Violations: Braces, Blocks, Method call work, etc.

- .rubocop.yml
- .rubocop_todo.yml
- CHANGELOG.md
- lib/cucumber/formatter/html.rb
- lib/cucumber/gherkin/formatter/ansi_escapes.rb
- lib/cucumber/gherkin/formatter/escaping.rb
- spec/cucumber/cli/configuration_spec.rb
- spec/cucumber/formatter/html_spec.rb
- spec/cucumber/multiline_argument/data_table_spec.rb
- spec/cucumber/step_match_search_spec.rb
Fixed
- Layout/IndentHeredoc
- Layout/IndentConsistency
- Layout/IndentIndentationWidth
- New violations from above fixes
> Fix Layout/IndentHeredoc, Consistency, IndentationWidth, and new violations

- README.md
Removed Ruby 2.1 from 'supported platforms' in the readme file, as Ruby >= 2.2 is required (as per the gemspec file).
To reduce confusion/improve accuracy of the Readme file.
N/A
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cucumber/cucumber-ruby/1282)
> README: Remove Ruby 2.1 from supported platforms.

- features/docs/formatters/usage_formatter.feature
- lib/cucumber/formatter/usage.rb
Currently, when running `cucumber -f stepdefs` against features which don't include step definitions, a lengthy stacktrace is shown to the user. This is thoroughly described [in issue #1285](https://github.com/cucumber/cucumber-ruby/issues/1285).
I've simply added a condition to prevent a `NoMethodError` from being raised, if a step hasn't been defined for a test case. When an error isn't raised, example snippets are printed to stdout, as shown in the following test case:
```
Scenario: Run with --format stepdefs when some steps are undefined
Given a file named "features/calculator.feature" with:
"""
Feature: Calculator
Scenario: Adding numbers
When I add 4 and 5
Then I should get 9
"""
When I run `cucumber -f stepdefs features/calculator.feature`
Then it should pass with:
"""
You can …
```
> Fixed lengthy stacktrace when running `cucumber -f stepdefs` when steps aren't defined

- lib/cucumber/formatter/html.rb
- spec/cucumber/formatter/html_spec.rb
_This has been copied directly from [the original issue](https://github.com/cucumber/cucumber-ruby/issues/1240)._
When `Cucumber::Formatter::Html` tries to render an error where `snippet_for` goes to the `else`-branch (line 581)
https://github.com/cucumber/cucumber-ruby/blob/84bc859a62220290383a0a8c80ebf6820a426b4c/lib/cucumber/formatter/html.rb#L575-L583
it returns a frozen string (because of `frozen_string_literal: true`). When the syntax gem is not installed, modifying the frozen string in the `snippet`-method (line 571) raises an error (`can't modify frozen String`).
https://github.com/cucumber/cucumber-ruby/blob/84bc859a62220290383a0a8c80ebf6820a426b4c/lib/cucumber/formatter/html.rb#L568-L573
To resolve this, I simply created a new string from the original one, rather than mutating …
> Improve HTML formatting when `frozen_string_literal` is enabled and the `Syntax` gem is not installed.

- features/docs/cli/retry_failing_tests.feature
- lib/cucumber/formatter/fail_fast.rb
When running with --fail-fast and --retry, the first failure causes Cucumber to want_to_quit.  This changes resets that flag to false if the scenario succeeds on retry.
See changes to retry_failing_tests.feature
> Make --fail-fast play nice with --retry

- .circleci/config.yml
- CHANGELOG.md
- cucumber.gemspec
> Upgrade gherkin and cucumber expressions

- .circleci/config.yml
This PR replaces the non-existent 9.1.16.0 image with the latest 9.2.0.0
one.
This only makes the tests **run**, it does not repair them.
I found out that the jruby build failed due to a missing image.
CircleCI throws away some older images when they're superseded by newer
ones. The latest GA version of JRuby is now 9.2.0.0.
I'll let the CI run.
> CircleCI: use jruby-9.2.0.0

- cucumber.gemspec
- features/docs/formatters/json_formatter.feature
- lib/cucumber/formatter/json.rb
- spec/cucumber/formatter/json_spec.rb
Change to use the gherkin step location in the Json formatter.
For test steps from scenario outlines use the line of the outline step instead of line of the example table row.
Fixes #1108 (a regression from v1.3.x).
Depends on cucumber/cucumber-ruby-core#150.
The automated test suite has been updated to verify this behavior.
> Change to use the gherkin step location in the Json formatter.

- features/docs/cli/dry_run.feature
- features/docs/cli/strict_mode.feature
- features/docs/exception_in_after_step_hook.feature
- features/docs/exception_in_around_hook.feature
- features/docs/exception_in_before_hook.feature
- features/docs/gherkin/background.feature
- features/docs/gherkin/outlines.feature
- features/docs/gherkin/using_descriptions.feature
- features/docs/work_in_progress.feature
- features/docs/writing_support_code/before_hook.feature
- features/docs/writing_support_code/tagged_hooks.feature
- lib/cucumber/events.rb
- lib/cucumber/events/gherkin_source_parsed.rb
- lib/cucumber/formatter/console.rb
- lib/cucumber/formatter/pretty.rb
- lib/cucumber/formatter/progress.rb
- lib/cucumber/multiline_argument/data_table.rb
- lib/cucumber/runtime.rb
- spec/cucumber/formatter/pretty_spec.rb
- spec/cucumber/formatter/spec_helper.rb
- spec/cucumber/glue/proto_world_spec.rb
Let the Pretty Formatter use events (instead of the obsolete legacy_api).
A few behavioral changes are introduced:
* the step preceding the After Step hook are no added to the exception backtrace for an exception from the After Step hook.
* exceptions are printed when the result is not #ok?(strict_setting), previously pending exceptions were printed also when the were #ok? (that is in non-strict mode).
* tables (data tables and examples tables) are not longer prettified, but printed as they appear in the feature file.
* the indentation of exceptions are sometimes slightly changes, to make more sense.
Requires cucumber/cucumber-ruby-core#155.
The removal of using the legacy_api in the `spec_helper.rb` is breaking the rspec test for the HTML Formatter.
See …
> Let the Pretty Formatter use events

- lib/cucumber/formatter/rerun.rb
- spec/cucumber/formatter/rerun_spec.rb
Let the Rerun Formatter handle flaky scenarios.
Let the Rerun Formatter detect the retry of scenarios, and only with the `--strict-flaky` options, include the flaky scenarios in the output.
The Rerun Formatter output should be empty if the exit code is zero. Without the `--strict-flaky` option flaky scenarios do not make the exit code non-zero.
The automated test suite has been updated to verify this behavior.
> Let the Rerun Formatter handle flaky scenarios

- cucumber.yml
- features/docs/cli/randomize.feature
- features/docs/writing_support_code/around_hooks.feature
- lib/cucumber/cli/options.rb
- lib/cucumber/glue/hook.rb
Remove the support of old style tag expressions.
Remove the support for "~" and "," in tag expressions.
Still support the use of `~@no-clobber` tagged hooks in aruba (that is convert '`~@no-clobber`' to '`not @no-clobber`').
Old style tag expressions have been deprecated since v3.0.0, so their support should be removed in v4.0.0.
The automated test suite has been updated to verify the changed behavior.
> Remove the support of old style tag expressions.

- Gemfile
This PR suppresses the following warnings.
```console
% bundle install
The git source `git://github.com/cucumber/cucumber-ruby-core.git` uses
the `git` protocol, which transmits data without encryption. Disable
this warning with `bundle config git.allow_insecure true`, or switch to
the `https` protocol to keep your data secure.
The git source `git://github.com/cucumber/cucumber-ruby-wire.git` uses
the `git` protocol, which transmits data without encryption. Disable
this warning with `bundle config git.allow_insecure true`, or switch to
the `https` protocol to keep your data secure.
Fetching git://github.com/cucumber/cucumber-ruby-core.git
Fetching git://github.com/cucumber/cucumber-ruby-wire.Git
```
Refer: bundler/bundler#4127
> Use secure protocol when running `bundle install`

- Gemfile
- cucumber.gemspec
- features/docs/cli/i18n.feature
- features/docs/gherkin/background.feature
- features/docs/gherkin/expand_option_for_outlines.feature
- lib/cucumber/events/gherkin_source_parsed.rb
- lib/cucumber/formatter/ast_lookup.rb
- lib/cucumber/formatter/json.rb
- lib/cucumber/formatter/pretty.rb
- lib/cucumber/gherkin/data_table_parser.rb
- lib/cucumber/gherkin/steps_parser.rb
- lib/cucumber/runtime/support_code.rb
- spec/cucumber/formatter/pretty_spec.rb
Update to use gherkin version 6.
Update to use gherkin version 6.
The pretty formatter will not output anything about the rule keywords from the feature file, but it will produce some more or less reasonable output for features using the rule keyword.
For some unknown reasons the junit formatter will remove leading tab signs that were previously printed for stack traces from test cases from scenario outlines.
Depends on cucumber/cucumber-ruby-core#158
Needed to use gherkin version 6.
The automated test suite has been updated to verify this behavior.
> Use gherkin 6

- lib/cucumber/formatter/interceptor.rb
- spec/cucumber/formatter/interceptor_spec.rb
Fix two tests that were failing.
The test suite was failing with:
```
1) Cucumber::Formatter::Interceptor::Pipe#unwrap! disables the pipe bypass
Failure/Error: raise "This method is due for removal after version #{remove_after_version}" if Cucumber::VERSION > remove_after_version
RuntimeError:
This method is due for removal after version 3.99
2) Cucumber::Formatter::Interceptor::Pipe#write adds the buffer to its stored output
Failure/Error: raise "This method is due for removal after version #{remove_after_version}" if Cucumber::VERSION > remove_after_version
RuntimeError:
This method is due for removal after version 3.99
```
The method `Cucumber::Formatter::Interceptor::Pipe#buffer` has been scheduled for removal before version 4.0.0 is released.
I removed this method and migrated tests …
> Remove deprecated method

- features/docs/defining_steps/snippets.feature
- features/docs/formatters/usage_formatter.feature
- features/docs/gherkin/using_star_notation.feature
- lib/cucumber/glue/snippet.rb
- spec/cucumber/formatter/pretty_spec.rb
- spec/cucumber/glue/snippet_spec.rb
Update the missing step generation template to use single-quotes for strings instead of double-quotes.
When pending steps are generated for undefined steps, the step name does
not include any interpolation so double-quotes are not necessary. Only
the single-quotes are necessary for those strings.
This will make the generated steps allow consistent with the ruby style guide:
https://github.com/rubocop-hq/ruby-style-guide#strings
And with the default settings for Rubocop Style/StringLiterals cop:
https://github.com/rubocop-hq/rubocop/blob/ab6346ed37d88a4b900c96979f8ef18959e8dcce/lib/rubocop/cop/style/string_literals.rb
This will make it easier to use the generated steps, in a project using Rubocop, by making those steps already back the default Rubocop rules.
I have updated the existing …
> Use single quotes in generated template steps

- lib/cucumber/cli/options.rb
- lib/cucumber/configuration.rb
- spec/cucumber/configuration_spec.rb
Causes Cucumber to load `env.rb` files even on dry run.
This PR removes a conditional in `configuration.rb` that prevents env files from loading when the `--dry-run` option is turned on. It also updates the help message for `--dry-run` to omit the part about env files not loading.
In #1324, @dpsi brings up an issue they're having loading constants and libraries when Cucumber runs under the `--dry-run` option, pointing out that this is [not the first time](https://groups.google.com/d/msg/cukes/Kucz1T_VBss/VkEUBpY6MQAJ) users have brought up this problem with us. The issue stems from the `env.rb` files not being loaded.
The test ensuring that env files are not loaded on dry runs has been removed. I've ensured that env files do still load first in all cases.
> Update code to include env files in dry run

- Rakefile
- cucumber.yml
#1329 is big and not focused, so I'm splitting it.
This PR changes the default profile that we run in CI and locally to run more specs.
I noticed that running `bundle exec cucumber` run way more specs than running `bundle exec rake cucumber`.
As far as I understand it, we're running a lot less features than we should. There's no reason to not run the "@todo-windows"-tagged scenarios by default, unless we're on Windows... right?
Prevention of regressions.
Locally, via `bundle exec rake cucumber`.
> Run full specs

- CHANGELOG.md
- features/docs/cli/randomize.feature
- features/lib/step_definitions/cucumber_steps.rb
- lib/cucumber/cli/configuration.rb
- lib/cucumber/configuration.rb
While debugging some apparently order dependent failures on my cucumber scenarios, I noticed that it's currently impossible to reproduce order dependent failures, because the seed cucumber says it has used is not the seed it has really used.
My changes make sure that the seed that cucumber uses to randomize the scenarios is the same that cucumber informs in the UI, so the same scenario order can actually be reproduced in subsequent runs.
In order to test this, I needed to use some stuff from newer versions of `aruba`, so I upgraded the scenarios to use that first. Happy to extract that to a separate PR, of course.
This change makes it possible to reproduce order dependent failures when running scenarios in random order. Previously, it was not working.
I added a test that runs cucumber in …
> Fix randomization seed

- lib/cucumber/cli/options.rb
When I read the help text for the --require option, it was conceivable
that the text could have been interpreted in at least two ways.
This commit aims to clarify the help text to reduce ambiguity/improve
the clarity of the behavior of the option, espcially with respect to the
loading of files under "support" directories.
This change did not require any additional tests. Though, of course, all tests were run to ensure no existing tests were broken by this change.
I'm not sure if this requires a change to the documentation. If it does, I'd be more than happy to make that change&mdash;though, I don't know where that documentation is. Is it in a separate repository?
> Updates --require option help text

- lib/cucumber/configuration.rb
- spec/cucumber/configuration_spec.rb
Fixes the load order of `env.rb` files
According to The Cucumber Book on pp. 129-130:
> Just like `features/step_definitions`, Cucumber will load all Ruby files it finds in `features/support`. This is convenient, because it means you don't need to pepper `require` statements everywhere, but it does mean that the precise order in which files are loaded is hard to control. In practice, this means you can't have dependencies between files in the `support` directory, because you can't expect that another file will have already been loaded. There is one exception to that, a special file called `env.rb`.
>
> The file `features/support/env.rb` is always the very first file to be loaded when Cucumber starts a test run.
This is also extened such that any `env.rb` file located in descendant …
> Fixes env.rb and support files load order

- lib/cucumber/formatter/backtrace_filter.rb
- spec/cucumber/formatter/backtrace_filter_spec.rb
The Ruby might be configured to be installed into various locations. Be smarter about filtering backtrace to properly remove all traces of standard library.
Fixes #1341.
> Respect Ruby configuration when filtering backtrace.

- CHANGELOG.md
- lib/cucumber/cli/main.rb
fixes #988
Basically now first `Ctrl+C` will terminate scenario execution but will stil execute `at_exit` hooks. Second `Ctrl+C` will also interrupt that.
see #988
In the past first `Ctrl+C` only told Cucumber to exit after this scenario. And a second one terminated immediately without `at_exit` hooks. So there was no way to interrupt immediately but still execute `at_exit`. This could lead to tested system to remain in inconsistent state and require manual restore.
Not sure how can I test this.
I editted my local copy of the gem and run a test scenario
```
$  cucumber features/long_feature.feature 
Feature: Long running scenarios
@clean-up
Scenario: 100 seconds with clean-up # features/long_feature.feature:4
Given I love you                  # features/step_definitions/gah.rb:1
hey
^C …
```
> SIGINT trap consistent with TERM behaviour

- .circleci/config.yml
- CHANGELOG.md
Removing a failing task from circleCI
It's long been failing, and was added a while back: https://github.com/cucumber/cucumber-ruby/commit/24e3a2ec659a02ee7797375178de19eac7e41d0f
In the SHA @mattwynne you mention adding an SSH key. Was this done? As it keeps failing for invalid authentication
Just trying to tidy up the build process with @olleolleolle to get everything green and trustworthy again
> Remove cucumber pro publish job

- spec/cucumber/cli/options_spec.rb
> Fix a test case description typo

- lib/cucumber/formatter/duration_extractor.rb
- lib/cucumber/formatter/json.rb
- lib/cucumber/formatter/junit.rb
Support embeddings listed in step results.
I'm looking into cucumber-cpp for my company.
We need to be able to embed text or images into the reports, but that feature is not available when using the wire protocol.
This patch is the 1st of a series a 4, respectively impacting _cucumber-ruby_, _cucumber-ruby-core_, _cucumber-ruby-wire_ and _cucumber-cpp_.
Basically, the idea is to allow embeddings to be specified in the success or fail responses sent through the wire protocol. E.g.:
```
["success",{"embeddings":[{"label":"Embedded text","mime_type":"text/plain","src":"Some text"}]}]
["fail",{"embeddings":[{"label":"Embedded image","mime_type":"image/png;base64","src":"iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAYAAAAfFcSJAAAADUlEQVR42mP8z8BQDwAEhQGAhKmMIQAAAABJRU5ErkJggg=="}],"message":"There was no …
```
> Support embeddings stored in step results

- lib/cucumber/formatter/json.rb
- spec/cucumber/formatter/json_spec.rb
Fix the placeholder expansions in the json formatter.
It is the test case name - in which scenario outline placeholders are expanded - that shall be used by the json formatter, and not the scenario name.
Bugfix - now when the Gherkin library compiler are used in Cucumber-Ruby, which does expand scenario outline placeholders also in scenario names.
The automated test suite has been updated to verify this behavior.
> Fix the placeholder expansions in the json formatter

- lib/cucumber/multiline_argument/data_table.rb
`cucumber-ruby-wire` build is failing after upgrading `cucumber-ruby` and `cucumber-ruby-core` to `gherkin` 9. Some tests are fixed (see [`cucumber-ruby-wire#25`](https://github.com/cucumber/cucumber-ruby-wire/pull/25) but one test is still failing (and should be fixed by this PR).
What is happening (as far as I can tell) is that we try to serialise the `DataTable` to `json`, but the `to_hash` method on `DataTable` requires an argument.
This proposal renames the previous `to_hash` method as `cells_to_hash` and creates a `to_hash` method providing a matrix of the cells value.
This was a bit retro-engineered based  on what was expected by the test, that's a part of the code I'm definitely not familiar with, so any input is more than welcome.
> Fix troubles with DataTable.to_hash in cucumber-ruby-wire

- features/docs/formatters/json_formatter.feature
- features/docs/post_configuration_hook.feature
- features/lib/step_definitions/aruba_steps.rb
- features/lib/support/normalise_output.rb
- lib/cucumber/cli/options.rb
- lib/cucumber/deprecate.rb
- lib/cucumber/formatter/json.rb
- spec/cucumber/deprecate_spec.rb
As we now have a `message`formatter working and that has been tested with the new stand-alone `json-formatter`, we can deprecate the old json-formatter.
> Deprecate json formatter

- Gemfile
- lib/cucumber/configuration.rb
- lib/cucumber/runtime.rb
- spec/cucumber/formatter/query/hook_by_test_step_spec.rb
- spec/cucumber/formatter/query/pickle_by_test_spec.rb
- spec/cucumber/formatter/query/pickle_step_by_test_step_spec.rb
- spec/cucumber/formatter/query/step_definitions_by_test_step_spec.rb
Original idea behind CCK was to have predictable ids for comparing messages, but the way we compare messages in CCK (using `json-formatter`) makes this useless finally.
See [cucumber-ruby-core#195](https://github.com/cucumber/cucumber-ruby-core/pull/195)
> Use IdGenerator::UUID 

- features/docs/defining_steps/nested_steps.feature
- features/docs/defining_steps/nested_steps_i18n.feature
- features/docs/defining_steps/nested_steps_with_second_arg.feature
- features/docs/defining_steps/printing_messages.feature
- features/docs/formatters/json_formatter.feature
- features/docs/formatters/pretty_formatter.feature
- features/docs/getting_started.feature
- features/docs/gherkin/doc_strings.feature
- features/docs/writing_support_code/after_hooks.feature
- lib/cucumber/deprecate.rb
- lib/cucumber/errors.rb
- lib/cucumber/formatter/console.rb
- lib/cucumber/formatter/duration_extractor.rb
- lib/cucumber/formatter/json.rb
- lib/cucumber/formatter/junit.rb
- lib/cucumber/formatter/message.rb
- lib/cucumber/formatter/pretty.rb
- lib/cucumber/glue/proto_world.rb
- lib/cucumber/runtime/for_programming_languages.rb
- lib/cucumber/runtime/user_interface.rb
- spec/cucumber/deprecate_spec.rb
- spec/cucumber/glue/proto_world_spec.rb
- spec/cucumber/glue/step_definition_spec.rb
Following discussions in [cucumber#897](https://github.com/cucumber/cucumber/issues/897)
> Deprecate puts and embed

- features/lib/step_definitions/messages_steps.rb
- lib/cucumber/formatter/message.rb
`log` did not correctly create `attachment` messages.
> Correctly handle 'log' in messages formatter

- features/docs/formatters/gherkin_6.feature
After discussions around the [Yak map](https://app.mindmup.com/map/_v2/2b5ee9a00d1b11ea85574541c004362d) today, one thing left before cutting 4.0 final was enduring the existing formatters work fine with Gherkin 6+ notations.
> Add feature file showing the formatters work fine with Gherkin 6+ syntax

- features/docs/defining_steps/snippets.feature
- lib/cucumber/glue/snippet.rb
- spec/cucumber/glue/snippet_spec.rb
When you have a step with a string argument and a Doc String argument, the generated snippet contains a duplicate argument name
This scenario currently fails
```gherkin
Scenario: Snippet for undefined step with combined arguments
Given a file named "features/undefined_steps.feature" with:
"""
Feature:
Scenario: combined step
Given a "thing" with:
\"\"\"
thing
\"\"\"
"""
When I run `cucumber features/undefined_steps.feature -s`
Then the output should contain:
"""
Given('a {string} with:') do |string, string2|
pending # Write code here that turns the phrase above into concrete actions
end
"""
```
> Fix code snippet on docstring

- lib/cucumber/formatter/interceptor.rb
Move initialization of the `Mutex` to the constructor.
We need the lock for the primary concern of this class, write & read synchronized.
There's no benefit to waiting to initialize the Mutex.
Avoid concurrency interaction trouble on non-MRI platforms.
Squinting.
> Avoid lazy init of mutex by moving it to constructor

- CHANGELOG.md
- features/docs/defining_steps/snippets.feature
- lib/cucumber/events.rb
- lib/cucumber/events/undefined_parameter_type.rb
- lib/cucumber/formatter/console.rb
- lib/cucumber/formatter/message_builder.rb
- lib/cucumber/formatter/pretty.rb
- lib/cucumber/formatter/progress.rb
- lib/cucumber/glue/registry_and_more.rb
> Display snippet for missing parameter types

- CHANGELOG.md
- lib/cucumber/errors.rb
- lib/cucumber/glue/proto_world.rb
- spec/cucumber/glue/proto_world_spec.rb
- spec/cucumber/glue/step_definition_spec.rb
> Enable logging non-string - fix #1410

- lib/cucumber/cli/options.rb
Follow up of #1415
Display an up to date message for the `-o` option when running `cucumber -h`
> Fix documentation for --out=url

- cucumber.gemspec
`diff-lcs` got a [new release yesterday (1.4)](https://github.com/halostatue/diff-lcs/blob/master/History.md#14--2020-06-23).
Although this is marked as a minor upgrade, the API changed and makes our CI fail. Until this is more cleanly fixed, we'll stick to 1.3.
> Force diff-lcss < 1.4

- Gemfile
Thanks to #1426 - there was a reference left to Aruba in the `Gemfile`, this removes it as we don't rely on Aruba anymore.
> Remove Aruba reference in Gemfile

- CHANGELOG.md
- lib/cucumber/runtime/step_hooks.rb
- lib/cucumber/runtime/support_code.rb
- spec/cucumber/formatter/query/hook_by_test_step_spec.rb
When an `AfterStep` hook is defined, the lookup for the Hook fails when trying to produce the messages.
See #1433 for more details.
> Fix AfterStep Hook lookup

- CHANGELOG.md
- cucumber.gemspec
- lib/cucumber/multiline_argument/data_table/diff_matrices.rb
Cucumber-ruby does not work with the latest version of diff-lcs.
`Array#flatten` works recursively and (apparently) operates on anything that supports `#to_ary`. Diff-lcs 1.4 added `Diff::LCS::Change#to_ary`. Because of this `DiffMatrices#changes` raises an error. This pull request avoid flattening of Diff::LCS::Change objects by limiting flattening to one level.
> Support diff-lcs 1.4

- CHANGELOG.md
- lib/cucumber/formatter/interceptor.rb
- spec/cucumber/formatter/interceptor_spec.rb
See #1445 
The trouble came from `method_missing` in the interceptor which called `super` when the method called on the stream did not return a value.
This is a piece of code showing the same kind of issue:
```ruby
class FakePipe
def no_return_value
puts "No, I won't return anything"
end
def with_return_value
puts "I let something here before returning a value"
return 1
end
end
class FakeInterceptor
def initialize
@pipe = FakePipe.new()
end
def method_missing(method, *args, &blk)
@pipe.send(method, *args, &blk) || super
end
end
interceptor = FakeInterceptor.new()
interceptor.with_return_value # calls  `with_return_value` on the fake stream and does not call super 
interceptor.no_return_value   # calls `no_return_value` on the fake stream, then `super` which fails.
```
I've check in the …
> Fix errors when running JUnit reporter

- .circleci/config.yml
This removes support for Ruby 2.3 and 2.4 as they are now unsupported ruby versions.
This does not mean Cucumber won't work on those rubies. It just means we no longer verify that it does. The reason for this is that some gems we depend on require ruby >= 2.5.
> Update CI, remove support for unsupported rubies

- CHANGELOG.md
- lib/cucumber/formatter/http_io.rb
- lib/cucumber/formatter/io.rb
- spec/cucumber/formatter/http_io_spec.rb
Prior to this change, all `IO` objects created by `ensure_io` would be flushed and closed when Ruby exits.
This turned out to be a problem for the new `--publish` functionality if Cucumber raised an exception.
One case where Cucumber will raise an exception (and not run anything) is when it's passed a non-existent feature file. It might also raise exceptions in other cases, for example when a feature file has syntax errors.
In those cases (where cucumber doesn't run anything), we don't want to publish any reports! However, since formatters (and their streams) are created *before* the exceptions described above are raised, it would already have registered the `at_exit` hooks that flush and close the streams (which in the case of `--publish` will publish a report).
The fix is to *defer* the …
> Defer at exit io close

- CHANGELOG.md
- lib/cucumber/cli/options.rb
- lib/cucumber/formatter/http_io.rb
- spec/cucumber/formatter/http_io_spec.rb
Doing a PUT directly and following redirects has issues as the body gets sent several times: once for initial request, and once for subsequent redirects. The initial request should be sent without any body and only the last one should contain the body.
Setting `--out 'url -X GET'` will request the given url with GET method, following redirects. If the response is a 202 Accepted *and* it has a Location HTTP header, then the payload is sent with a PUT request to the given location.
This approach is also a workaround for the limitation of Lambda payload size of 6 MB.
> Issue a PUT request after a GET request responding with 202 and a Location header

- CHANGELOG.md
- cucumber.gemspec
This follows  [cucumber#1168](https://github.com/cucumber/cucumber/pull/1168)
There is a security issue involved which was fixed by `cucumber-ruby-meta` 2.0.2, this change ensures we use the fixed version.
> Use cucumber-create-meta > 2.0.2

- lib/cucumber/cli/options.rb
Fixes a tiny typo, which my eye stumbles upon on any cucumber --help call.
> Fix typo in help output

- CHANGELOG.md
- lib/cucumber/formatter/http_io.rb
- spec/cucumber/formatter/http_io_spec.rb
A small improvement re: #1473 
Simply includes the response's body in the error message.
Here's an example:
```
$ # before
$ CUCUMBER_PUBLISH_URL="http://localhost:4567/422 -X GET" be cucumber --publish
Traceback (most recent call last):
2: from /home/jmks/.asdf/installs/ruby/2.7.2/lib/ruby/gems/2.7.0/gems/cucumber-5.1.3/lib/cucumber/formatter/io.rb:40:in `block (3 levels) in new'
1: from /home/jmks/.asdf/installs/ruby/2.7.2/lib/ruby/gems/2.7.0/gems/cucumber-5.1.3/lib/cucumber/formatter/http_io.rb:75:in `close'
/home/jmks/.asdf/installs/ruby/2.7.2/lib/ruby/gems/2.7.0/gems/cucumber-5.1.3/lib/cucumber/formatter/http_io.rb:128:in `send_content': request to http://localhost:4567/422 failed with status 422 (StandardError)
$ # after
$ CUCUMBER_PUBLISH_URL="http://localhost:4567/422 -X GET" be …
```
> Include response body when --publish errors

- CHANGELOG.md
- lib/cucumber/formatter/html.rb
- lib/cucumber/formatter/http_io.rb
- lib/cucumber/formatter/io.rb
- lib/cucumber/formatter/json.rb
- lib/cucumber/formatter/message.rb
- lib/cucumber/formatter/pretty.rb
- lib/cucumber/formatter/progress.rb
- lib/cucumber/formatter/rerun.rb
- lib/cucumber/formatter/steps.rb
- lib/cucumber/formatter/summary.rb
- lib/cucumber/formatter/url_reporter.rb
- spec/cucumber/formatter/http_io_spec.rb
- spec/cucumber/formatter/url_reporter_spec.rb
> --publish: use banner provided by the reports server

- CHANGELOG.md
- features/docs/formatters/junit_formatter.feature
- lib/cucumber/cli/options.rb
- lib/cucumber/formatter/junit.rb
- spec/cucumber/cli/options_spec.rb
- spec/cucumber/formatter/junit_spec.rb
Original work completed in #1471, but the owner isn't moving the code forward and I don't have access to the repo, so I forked and added the necessary CHANGELOG.
Original PR Description from #1471:
Allow for adding file= attribute to junit
Use cli arg -f junit,fileattribute=true
Is your pull request related to a problem? Please describe.
CircleCI has a test splitting feature that will split tests across multiple jobs based on the time spent. This feature requires a file attribute to be added. The cucumber-ruby test junit formatter does not include this attribute.
This adds a -f junit,fileattribute=true cli option that will add the file attribute to the <testcase/> elements in the …
> Add junit fileattribute

- lib/cucumber/cli/configuration.rb
- spec/cucumber/cli/configuration_spec.rb
https://github.com/cucumber/cucumber-ruby/issues/1468
Missing pretty formatter when using --publish
In cli/configuration, I have added the pretty formatter per default when only message(s) formatter(s) are specified.
> Add pretty formatter with publish

- .circleci/config.yml
- CHANGELOG.md
Install MSYS2 using Chocolatey allow a silent install.
Then, ridk can set-up msys2 properly and the ruby devkit.
The circle-ci windows build is broken
`ridk` may not be silent when installing `msys2`.
Installing `msys2` using `choco` allows to install it silently, then `ridk install 2 3` can properly set-up the ruby devkit.
> Fix windows build

- features/lib/support/env.rb
Re-set it properly after each tests to be able to actually publish our
own reports.
This is an attempt to fix our own GHA
Unset CUCUMBER_PUBLISH_TOKEN before each cucumber tests to avoid interference within the test.
Then reset it properly after each tests to be able to publish our own reports.
> Ignore CUCUMBER_PUBLISH_TOKEN during cucumber tests

- .circleci/config.yml
Refs. https://github.com/cucumber/cucumber-ruby/issues/1498
Add a job explicitly dedicated to ruby 3.0 in addition to the ruby:latest one
> Add a ruby 3.0 job to CI

- CHANGELOG.md
- cucumber.gemspec
- features/docs/raketask.feature
- features/docs/writing_support_code/attachments.feature
- features/lib/step_definitions/message_steps.rb
- lib/cucumber/formatter/json.rb
- lib/cucumber/glue/proto_world.rb
- spec/cucumber/formatter/json_spec.rb
Fixes #1506
We plan to allow attaching files by specifying their path
Cucumber will take care of opening and reading it.
> Allow attaching path

- README.md
Supported platform in the Readme is outdated.
I've added Ruby 2.7 and Ruby 3.0 as they are part of the CI.
Should we keep Ruby 2.3 and Ruby 2.4? They are not part of the CI anymore, so if it breaks, we won't actually know.
> Update supported platforms in the Readme

- CHANGELOG.md
- lib/cucumber/glue/proto_world.rb
- spec/cucumber/formatter/json_spec.rb
- spec/cucumber/formatter/pretty_spec.rb
- spec/cucumber/glue/proto_world_spec.rb
- spec/cucumber/glue/step_definition_spec.rb
Removal of deprecated code.
Code deprecated in 4.0.
We are about to release 6.0.
The removed code can be easily replaced with `attach` and `log` without any other change in the code.
> Remove deprecated `embed` and `puts`

- CHANGELOG.md
The original language of the changed item was rather confusing; it almost made it sound like the deprecation of `puts` was being reversed, and that `puts` is now preferred over `log`. But it also said that both `puts` _and_ `log` were deprecated in 4.0. I don't think that's the case or the intention of this CHANGELOG point.
My edits aim to make clear that `puts` has been deprecated, and the desire of the Cucumber Team is that `log` should be used in step definitions instead.
> Clarify removal of `puts` in CHANGELOG

- CHANGELOG.md
- features/docs/formatters/json_formatter.feature
- lib/cucumber/cli/options.rb
- lib/cucumber/formatter/json.rb
As discussed at our last community meeting, the JSON formatter is no more deprecated, but entering maintenance mode.
> Remove deprecation for the JSON formatter

- CHANGELOG.md
- features/docs/gherkin/empty_scenario.feature
- features/lib/support/json.rb
- lib/cucumber/formatter/json.rb
Fixes #1530
Empty scenarios are not reported in the json formatter.
In order to standardize support for empty scenario, one has been added in the CCK: https://github.com/cucumber/cucumber/pull/1498
cucumber-ruby has been chosen for reference, but yet the support could be improved.
That is the purpose of that PR
We report empty scenarios in the json formatter, with an empty `steps` array
> Report empty scenarios with the json formatter

- CHANGELOG.md
- lib/cucumber/glue/proto_world.rb
- spec/cucumber/glue/proto_world_spec.rb
Fixes #1529 
Rescue any standard error in the attach method, then call super without any further process around it
> Fix 'attach' when passing null byte in the data

- CHANGELOG.md
- lib/cucumber/step_match.rb
- spec/cucumber/glue/step_definition_spec.rb
Fixes #1532
Step arguments are delegated to the World since 144f34177efb9259c63e3f112edf85a47b11ce6b.
That prevent state to leak so the deep-clone seems not required anymore.
But at the moment, I have no idea how to test that properly, and how to make sure state cannot leak
> Remove deep clone of step arguments

- CHANGELOG.md
- lib/cucumber/formatter/ansicolor.rb
On the integrated terminal of vscode, Cucumber always warns about ANSICON as below.
```bash
*** WARNING: You must use ANSICON 1.31 or higher (https://github.com/adoxa/ansicon/) to get coloured output on Windows
```
This behavior was discussed in https://github.com/cucumber/cucumber-ruby/issues/1163 or https://github.com/cucumber/cucumber-ruby/pull/1119, but unfortunately has not resolved yet.
Because the environment variable `VSCODE_PID` mentioned in #1163 is already  obsolete, it seems to be good to check the value of `TERM_PROGRAM` instead of it.
- I have tested the above change with my local copy of the gem, and I am …
>  Suppress unnecessary warnings about ANSICON in integrated terminal of vscode

- .github/workflows/cucumber-ruby.yml
- CHANGELOG.md
- README.md
Refs. https://github.com/cucumber/cucumber-ruby/pull/1571
Due to issue with JRuby 9.3, I suggest to not support it until we have a solution
That would prevent delaying a potential release of cucumber-ruby
> Inform about non-support of JRuby 9.3

- CHANGELOG.md
This PR adds dates for all releases documented in CHANGELOG.md.
Fixes #1543 
> Restore release dates in CHANGELOG.md

- CHANGELOG.md
- lib/cucumber/formatter/ansicolor.rb
- lib/cucumber/term/ansicolor.rb
- spec/cucumber/formatter/ansicolor_spec.rb
> Refactor formatter/ANSIColor

- CHANGELOG.md
- UPGRADING.md
- features/lib/support/command_line.rb
- lib/cucumber/cli/main.rb
- spec/cucumber/cli/main_spec.rb
Remove the former unused stdin argument from Cli::Main.
Fixes #1581 
> Remove unused 3rd arg from Cli::Main

- CHANGELOG.md
- UPGRADING.md
- lib/cucumber/multiline_argument/data_table.rb
- spec/cucumber/multiline_argument/data_table_spec.rb
> Remove map_column! and map_headers!

- CHANGELOG.md
- UPGRADING.md
- lib/cucumber/multiline_argument/data_table.rb
- spec/cucumber/multiline_argument/data_table_spec.rb
> Change DataTable#map_column 'strict' argument to a keyword argument

- CHANGELOG.md
- lib/cucumber/multiline_argument/data_table.rb
- spec/cucumber/multiline_argument/data_table_spec.rb
> Fix map_headers when headers have the same prefix

- CHANGELOG.md
- cucumber.gemspec
- lib/cucumber/runtime.rb
- lib/cucumber/runtime/meta_message_builder.rb
- spec/cucumber/runtime/meta_message_builder_spec.rb
> Migrate from create-meta to ci-environment

- CHANGELOG.md
- features/docs/writing_support_code/world.feature
- lib/cucumber/glue/proto_world.rb
Fixes #1595
Make sure to extend the World with a valid Object rather than extending it with something we think is valid but may not be.
> Fix 1595: make sure to extend the world with a valid module

- .github/workflows/cucumber-ruby.yml
- CHANGELOG.md
Because Ruby 3.1.0 is now in general release, it makes sense to add Ruby 3.1 to the CI matrix
> Add Ruby 3.1 to the CI matrix

- .github/workflows/cucumber-ruby.yml
- .github/workflows/rubocop.yml
- CHANGELOG.md
- README.md
- Rakefile
- lib/cucumber/formatter/backtrace_filter.rb
Add Truffleruby support to CI
Extract Rubocop linting into separate workflow
> Add Truffleruby support

- .rubocop.yml
- CHANGELOG.md
- lib/cucumber/formatter/io.rb
- lib/cucumber/rake/task.rb
- spec/cucumber/rake/task_spec.rb
Fixes #1614 
- New feature (non-breaking change which adds new behaviour)
> Warn user when using space-separated string with cucumber_opts

- CHANGELOG.md
- cucumber.gemspec
This is the same change made in https://github.com/cucumber/cucumber-rails/pull/533.
`rubygems_version` is used, probably a mistake for `required_rubygems_version`.
Because `rubygems_version` should not be set.
refs: https://github.com/rubygems/rubygems/blob/2faada63ae65d8559bcba9e083f3c35ba6c18fdc/lib/rubygems/specification.rb#L536-L541
> Use `required_rubygems_version` instead of `rubygems_version`

- CHANGELOG.md
- examples/i18n/it/features/step_definitions/calcolatrice_steps.rb
- examples/i18n/no/features/step_definitions/kalkulator_steps.rb
- examples/i18n/pt/features/step_definitions/calculadora_steps.rb
- examples/i18n/ro/features/step_definitions/calculator_steps.rb
- examples/i18n/ru/features/step_definitions/calculator_steps.rb
- examples/i18n/sv/features/step_definitions/kalkulator_steps.rb
- examples/rspec_doubles/features/step_definitions/calvin_steps.rb
- spec/cucumber/cli/configuration_spec.rb
- spec/cucumber/formatter/junit_spec.rb
- spec/cucumber/glue/registry_and_more_spec.rb
- spec/cucumber/glue/step_definition_spec.rb
- spec/cucumber/step_match_search_spec.rb
- spec/cucumber/world/pending_spec.rb
This PR suppresses the following RSpec deprecation warnings.
* Pass a block instead of a lambda to `expect`
```
The implicit block expectation syntax is deprecated, you should pass a block rather than an argument to `expect` to use the provided block expectation matcher or the matcher must implement `supports_value_expectations?`. e.g  `expect { value }.to change `step_args.first`` not `expect(value).to change `step_args.first``
```
* Replace deprecated `should` with RSpec3's `expect`
```
DEPRECATION: Using `should` from rspec-expectations' old `:should` syntax without explicitly enabling the syntax is deprecated. Use the new `:expect` syntax or explicitly enable `:should` with `config.expect_with(:rspec) { |c| c.syntax = :should }` instead. Called from …
```
> Suppress RSspec deprecation warnings

- renovate.json
* add a custom [regex manager](https://docs.renovatebot.com/modules/manager/regex/) to the `renovate.json` config which allows Renovate to detect dependencies in `.gemspec` files.
Fixes #1637 
> Add rule to renovate config to examine gemspec too

- CHANGELOG.md
- lib/cucumber/formatter/ansicolor.rb
- spec/cucumber/formatter/ansicolor_spec.rb
This fixes a NoMethodError exception that is raised, when the environment variable `CUCUMBER_COLORS` is set, by allowing `apply_custom_colors` to be called right after its definition in `Cucumber::Formatter::ANSIColor`.
Defining the method as a class method of the module allows it to be called in the module itself.
> Fix NoMethodError that is raised when the environment variable CUCUMBER_COLORS is defined

- Gemfile
I've been working on trying to resolve https://github.com/cucumber/cucumber-ruby/issues/1637 and trying a different tack using Dependabot rather than Renovate.
In order to get Dependabot to parse our dependencies, we need to simplify the Gemfile to plain text.
This seems to work, [based on a test I did in my fork](https://github.com/mattwynne/cucumber-ruby/network/updates/389434839). It's even created a couple of PRs (https://github.com/mattwynne/cucumber-ruby/pull/2, https://github.com/mattwynne/cucumber-ruby/pull/3).
The downside is that we lose this fancy ability to configure our development environments. To me this feels like a good trade-off, as we can still un-comment these lines locally if we need to work on a particular library in conjunction with this one. I went for having them …
> Simplify Gemfile so dependabot can parse it

- CHANGELOG.md
- features/docs/cli/retry_failing_tests.feature
- features/lib/step_definitions/scenarios_and_steps.rb
- lib/cucumber/cli/options.rb
- lib/cucumber/configuration.rb
- lib/cucumber/filters/retry.rb
- spec/cucumber/cli/options_spec.rb
- spec/cucumber/filters/retry_spec.rb
This PR adds a new option `--retry-total` which can be used in conjunction with the existing option `--retry`.
`--retry-total` acts as a circuit breaker in case a larger number of tests are failing, and it comes apparent that the problem introduced is not the usual 'flakiness' that `--retry` deals with. For example, when a bad commit leads to many tests failing it is very inefficient and slow to retry all these tests. The same is true if a temporary infrastructure problem causes all tests to fail.
In our test suite of 24'000 tests, we observe a predictable number of tests being randomly flakey. This number is below 5 and therefore we would set `--retry 3 --retry-total 5`. In case of a bad commit with e.g. 3000 tests failing we would save the effort and time to repeat all of them 3 times. …
> New option '--retry-total' as a circuit breaker for option '--retry'

- .github/workflows/cucumber-ruby.yml
- .github/workflows/release.yml
- .github/workflows/rubocop.yml
- README.md
This PR is add Ruby 3.2 to the CI matrix
Because Ruby 3.2.0 is now in general release, it makes sense to add Ruby 3.2 to the CI matrix.
https://www.ruby-lang.org/en/news/2022/12/25/ruby-3-2-0-released/
- [-] RDoc comments have been updated
> Add Ruby 3.2 to the CI matrix

- CHANGELOG.md
- cucumber.gemspec
- lib/cucumber/glue/proto_world.rb
[mini_mime](https://github.com/discourse/mini_mime) is a minimal mime type library that's more performant and uses less memory than the `mime-types` gem.
It has replaced `mime-types` in several projects:
* `rails` →  `actionmailer` → `mail` gem: https://github.com/mikel/mail/pull/1059
* `capybara` https://github.com/teamcapybara/capybara/pull/1884
* `httparty` https://github.com/jnunemaker/httparty/pull/769
Using it as a dependency of `cucumber`, downstream projects would be able to reuse the same dependency that is already available in most Rails apps, instead of pulling in an extra `mime-types` dependency.
- Refactoring (of dependencies) (improvements to code design or tooling that don't change behaviour)
> Replace mime-types gem with mini_mime

- .github/workflows/cucumber-ruby.yml
- .github/workflows/release.yml
- .rubocop.yml
- CHANGELOG.md
- README.md
- cucumber.gemspec
Drop support for Ruby 2.6. Adresses  #1693
- Reducing technical debt
Please add an entry to the relevant section of CHANGELOG.md as part of this pull request. - Done :heavy_check_mark: 
This PR might fix the red build here: https://github.com/cucumber/cucumber-ruby/pull/1689
Changes are not required in cucumber.io/docs
> Drop Ruby 2.6 support

- CHANGELOG.md
- cucumber.gemspec
Hotfix from v9
If your change may impact future contributors, explain it here, and remember to update README.md and CONTRIBUTING.md accordingly.
If the [Cucumber documentation](https://cucumber.io/docs/) requires an update,
submit a PR to [cucumber/docs](https://github.com/cucumber/docs/) and
reference it here.
e.g. "Ref: cucumber/docs/pull/#99"
> Fix Unable to determine `VERSION`

- lib/cucumber/formatter/junit.rb
- spec/cucumber/formatter/junit_spec.rb
Fix up a small amount of styling
Remove open ended steps to avoid IDE issues.
Small tidies to jUnit legacy tests to keep them from being able to be debugged locally
> refactor/fix up jUnit tests

- CHANGELOG.md
- lib/cucumber/formatter/message_builder.rb
Attempts to fix [Handle NME from cucumber-wire](https://github.com/cucumber/cucumber-ruby-wire/issues/56)
> bugfix: Handle Cucumber-Wire issue when parameter type cannot be specified on Envelope

- CHANGELOG.md
- lib/cucumber/multiline_argument/data_table.rb
Ruby head adds a capacity keyword option to Hash which causes other keywords passed to `Hash.new` to be validated, this causes an error when running Cucumber 9.2.0 on ruby-head (example from an [rspec-expectations build](https://github.com/rspec/rspec-expectations/actions/runs/9930979288/job/27430326483?pr=1471)):
```
/home/runner/work/rspec-expectations/rspec-expectations/bin/cucumber
<internal:hash>:37:in 'initialize': unknown keywords: :strict, :proc (ArgumentError)
from /home/runner/work/rspec-expectations/rspec-expectations/bundle/ruby/3.4.0+0/gems/cucumber-9.2.0/lib/cucumber/multiline_argument/data_table.rb:78:in 'Class#new'
```
> Remove unknown hash keyword arguments

- CHANGELOG.md
- cucumber.gemspec
- base64 will no longer be part of the default gems starting from Ruby 3.4.0
- logger will no longer be part of the default gems starting from Ruby 3.5.0
New explicit dependencies to avoid warnings:
- lib/cucumber.rb:7: warning: logger was loaded from the standard library, but will no longer be part of the default gems starting from Ruby 3.5.0.
- lib/cucumber/formatter/message.rb:4: warning: base64 was loaded from the standard library, but will no longer be part of the default gems starting from Ruby 3.4.0.
- New feature (non-breaking change which adds new behaviour)
- Breaking change (will cause existing …
> Avoid warning by explicit new dependencies

- cucumber.gemspec
I noticed that the project already has a FUNDING.yml. This PR adds the `funding_uri` to your gemspec to help increase visibility using the `bundle fund` command in Bundler.
> Add funding_uri to gemspec

- CHANGELOG.md
- lib/cucumber/multiline_argument/data_table.rb
- spec/cucumber/glue/snippet_spec.rb
- spec/cucumber/multiline_argument/data_table_spec.rb
Fixes up any remaining items into `main` from the 9.2 backported fix
Also fix up some associated code nearby to do with unindenting (This should now all be removed)
> Reintroduce cleaned up 9.2.1 into `main`

- .github/workflows/test.yaml
- CHANGELOG.md
- features/docs/extending_cucumber/custom_formatter.feature
- lib/cucumber/formatter/backtrace_filter.rb
- lib/cucumber/glue/invoke_in_world.rb
- spec/cucumber/glue/proto_world_spec.rb
Cucumber performs filtering and formatting on error backtraces before displaying them in terminal output.
When running on Ruby 3.4, the backtrace filtering and formatting is not working. This is defect is caused by the new backtrace format introduced in Ruby 3.4.
See:
- https://www.ruby-lang.org/en/news/2024/12/25/ruby-3-4-0-released/
- https://bugs.ruby-lang.org/issues/16495
- https://bugs.ruby-lang.org/issues/19117
Update the `Cucumber::Glue::InvokeInWorld` and `Cucumber::Formatter::BacktraceFilter` classes to support both styles of backtraces.
Fixes #1770
> Fix error backtrace formatting on Ruby 3.4+

- CHANGELOG.md
- lib/cucumber/formatter/message_builder.rb
Handle blank media type better when using base64 images
> bugfix: Handle blank media types
